"""
IBD Combo Prioritization Report Generator (offline, standalone HTML).

Produces a fully self-contained HTML report:
- Plotly.js bundle inlined ONCE (~4.8 MB).
- Combo-level signature heatmaps embedded as Plotly figures (data/layout JSON).
- Per-sample expression plots embedded as Plotly figure JSON.

Single-cell results (sc_target_result/) are generated by the pipeline but NOT
embedded in the report — they would inflate it 40-80+ MB. View them on disk.

Inputs are read directly from ``test/omicsoft_full/<COMBO_SLUG>/`` (no
``results/`` indirection for the omicsoft artifacts), plus the scoring
pipeline which still reads through ``load_all_data(base_dir=...)``.

Usage:
    python tools/generate_ibd_report.py
    python tools/generate_ibd_report.py --output reports/IBD_Custom.html
"""

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from target_prioritization.data_loaders import load_all_data
from target_prioritization.scoring import calculate_overall_scores

import jinja2


BASE_DIR = Path(__file__).parent.parent
TEMPLATE_PATH = BASE_DIR / "target_prioritization" / "templates" / "combo_prioritization_report_template.html"
OUTPUT_DIR = BASE_DIR / "reports"
CONFIG_PATH = BASE_DIR / "pipeline_config.json"
OMICSOFT_DIR = BASE_DIR / "test" / "omicsoft_full"

GENE_APPROACHES = {
    "GLP2R": "agonist",
}

# SC studies are produced by the pipeline (sc_target_result/) but NOT embedded
# in the report HTML — they add 40-80 MB of base64 iframes that inflate the
# file past usable sizes. View them directly on disk.

# Combo-level Plotly HTML exports (extracted into PLOT_FIGS as data/layout).
COMBO_LEVEL_PLOTS = ["comparison_signature", "target_signature"]




def load_config():
    with open(CONFIG_PATH) as f:
        return json.load(f)


def format_combo_name(combo):
    return " + ".join(combo)


def combo_slug(combo):
    return "_".join(combo)


def combo_anchor(combo):
    return "combo-" + "-".join(g.lower() for g in combo)


def gene_anchor(gene):
    return "gene-" + gene.lower()


def find_combo_dir(combo):
    """Locate the test/omicsoft_full/<slug>/ for a combo."""
    slug = combo_slug(combo)
    direct = OMICSOFT_DIR / slug
    if direct.is_dir():
        return direct
    return None


# ---------------------------------------------------------------------------
# Plotly bundle + figure extraction
# ---------------------------------------------------------------------------

def extract_plotly_bundle():
    """Pull the inlined plotly.js bundle out of a target_signature HTML.

    Scans ``test/omicsoft_full/*/target_signature_*.html`` and returns the
    first script block longer than 100 KB that contains the "plotly.js"
    banner. Returns an empty-bundle comment if nothing usable is found.
    """
    candidates = sorted(OMICSOFT_DIR.glob("*/target_signature_*.html"))
    for html_path in candidates:
        try:
            content = html_path.read_text(errors="ignore")
        except Exception:
            continue
        for match in re.finditer(r"<script\b[^>]*>(.*?)</script>", content, re.DOTALL):
            body = match.group(1)
            if len(body) > 100_000 and "plotly.js" in body[:2000].lower():
                return body
    return "/* Plotly bundle not found — interactive charts will not render. */"


def _parse_balanced(s, start, open_ch, close_ch):
    """Return (end_idx_exclusive, parsed_value) for the JSON expression that
    begins at ``s[start]``. Handles nested brackets and string-aware bracket
    counting. Returns ``(start, None)`` on failure.
    """
    if start >= len(s) or s[start] != open_ch:
        return start, None
    depth = 0
    i = start
    in_str = False
    escape = False
    n = len(s)
    while i < n:
        ch = s[i]
        if in_str:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_str = False
        else:
            if ch == '"':
                in_str = True
            elif ch == open_ch:
                depth += 1
            elif ch == close_ch:
                depth -= 1
                if depth == 0:
                    end = i + 1
                    try:
                        return end, json.loads(s[start:end])
                    except json.JSONDecodeError:
                        return start, None
        i += 1
    return start, None


def extract_plotly_figure(html_path):
    """Extract ``data`` / ``layout`` / ``config`` from a Plotly HTML export.

    Locates a ``Plotly.newPlot("<div_id>", [data], {layout}, {config})`` call
    that creates a real chart (skipping incidental occurrences inside the
    plotly bundle itself) and JSON-decodes its arguments.
    """
    try:
        content = Path(html_path).read_text(errors="ignore")
    except Exception:
        return None

    # Walk every occurrence of `Plotly.newPlot(` and try to parse one whose
    # first non-whitespace argument is a quoted div-id string.
    pat = re.compile(r"Plotly\.newPlot\(\s*\"")
    for m in pat.finditer(content):
        # Position of opening quote of the div-id.
        i = m.end() - 1  # last char in match is the opening quote
        # Find matching closing quote (no internal escapes expected for uuids).
        end_quote = content.find('"', i + 1)
        if end_quote == -1:
            continue
        # Walk past comma + whitespace to the data array.
        j = end_quote + 1
        while j < len(content) and content[j] in " ,\t\n\r":
            j += 1
        if j >= len(content) or content[j] != "[":
            continue
        data_end, data = _parse_balanced(content, j, "[", "]")
        if data is None:
            continue
        k = data_end
        while k < len(content) and content[k] in " ,\t\n\r":
            k += 1
        if k >= len(content) or content[k] != "{":
            continue
        layout_end, layout = _parse_balanced(content, k, "{", "}")
        if layout is None:
            continue
        # Optional config.
        config = {"responsive": True}
        m2 = layout_end
        while m2 < len(content) and content[m2] in " \t\n\r":
            m2 += 1
        if m2 < len(content) and content[m2] == ",":
            m2 += 1
            while m2 < len(content) and content[m2] in " \t\n\r":
                m2 += 1
            if m2 < len(content) and content[m2] == "{":
                _, cfg = _parse_balanced(content, m2, "{", "}")
                if cfg is not None:
                    config = cfg
        return {"data": data, "layout": layout, "config": config}
    return None






def build_persample_figures(combo):
    """Extract per-sample target_expression plots as Plotly figure dicts.

    Returns a list of (key, fig) pairs keyed as ``<study>::<plot_stem>``. The
    per-sample HTML exports are small enough (~5 MB, mostly the plotly bundle)
    that the extracted figure JSON is only ~40 KB each, so embedding them in
    PLOT_FIGS keeps the report compact and reuses the single inlined plotly
    bundle.
    """
    combo_dir = find_combo_dir(combo)
    if combo_dir is None:
        return []
    sample_root = combo_dir / "sample_level"
    if not sample_root.is_dir():
        return []

    out = []
    for study_dir in sorted(p for p in sample_root.iterdir() if p.is_dir()):
        for html_file in sorted(study_dir.glob("*.html")):
            fig = extract_plotly_figure(html_file)
            if fig is None:
                continue
            key = f"{study_dir.name}::{html_file.stem}"
            out.append((key, fig))
    return out


def build_archs4_figures(combo):
    """Extract ARCHS4 tissue expression plots as Plotly figure dicts."""
    slug = combo_slug(combo)
    archs4_dir = BASE_DIR / "test" / "archs4"
    out = []
    for plot_type in ["boxplot", "heatmap"]:
        html_path = archs4_dir / f"{slug}_{plot_type}.html"
        if html_path.exists():
            fig = extract_plotly_figure(html_path)
            if fig is not None:
                key = f"{plot_type}"
                out.append((key, fig))
    return out


def build_cellxgene_figures(combo):
    """Extract cellxgene per-celltype coexpression heatmaps as Plotly figure dicts."""
    slug = combo_slug(combo)
    cellxgene_dir = BASE_DIR / "test" / "cellxgene"
    if not cellxgene_dir.is_dir():
        return []
    out = []
    for celltype_dir in sorted(p for p in cellxgene_dir.iterdir() if p.is_dir()):
        celltype = celltype_dir.name
        html_path = celltype_dir / f"{celltype}_{slug}_heatmap.html"
        if html_path.exists():
            fig = extract_plotly_figure(html_path)
            if fig is not None:
                out.append((celltype, fig))
    return out


# ---------------------------------------------------------------------------
# Combo-level Plotly figures (extracted into PLOT_FIGS)
# ---------------------------------------------------------------------------

def collect_combo_level_figs(combo):
    """Extract combo-level signature/GSEA plots as Plotly figure dicts."""
    combo_dir = find_combo_dir(combo)
    if combo_dir is None:
        return {}
    anchor = combo_anchor(combo)
    figs = {}
    for plot_name in COMBO_LEVEL_PLOTS:
        matches = sorted(combo_dir.glob(f"{plot_name}_*.html"))
        if not matches:
            continue
        fig = extract_plotly_figure(matches[-1])  # newest by name (date suffix)
        if fig is not None:
            figs[f"{anchor}::{plot_name}"] = fig
    return figs


# ---------------------------------------------------------------------------
# Narrative / supporting content
# ---------------------------------------------------------------------------

def markdown_to_html(md_text):
    if not md_text:
        return ""
    html = md_text
    html = re.sub(r"^### (.+)$", r"<h4>\1</h4>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)
    html = re.sub(r"^- (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)
    html = re.sub(r"(<li>.*?</li>(\s*<li>.*?</li>)*)", r"<ul>\1</ul>", html, flags=re.DOTALL)
    out = []
    for line in html.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("<"):
            out.append(line)
        else:
            out.append(f"<p>{line}</p>")
    return "\n".join(out)


def extract_narrative_section(md_content, target_slug):
    if not md_content:
        return "<p>No narrative available.</p>"
    target_genes = target_slug.split("_")
    lines = md_content.split("\n")
    relevant = []
    capturing = False
    for line in lines:
        if any(g in line for g in target_genes) and (line.startswith("#") or line.startswith("**")):
            capturing = True
            relevant.append(line)
        elif capturing:
            if line.startswith("#") and not any(g in line for g in target_genes):
                break
            relevant.append(line)
    if relevant:
        return markdown_to_html("\n".join(relevant[:30]))
    return markdown_to_html("\n".join(lines[:20]))


def load_pathway_narrative(combo, results_dir):
    pathway_dir = results_dir / "pathwaydb_ibd"
    if not pathway_dir.exists():
        return "<p>Pathway data not available.</p>"
    for md_file in pathway_dir.glob("*summary*.md"):
        content = md_file.read_text(errors="ignore")
        return extract_narrative_section(content, combo_slug(combo))
    return "<p>No pathway summary found.</p>"


def load_ppi_narrative(combo, results_dir):
    ppi_dir = results_dir / "interactdb_ibd"
    if not ppi_dir.exists():
        return "<p>PPI data not available.</p>"
    for md_file in ppi_dir.glob("*summary*.md"):
        content = md_file.read_text(errors="ignore")
        return extract_narrative_section(content, combo_slug(combo))
    return "<p>No PPI summary found.</p>"


def load_gene_overview(gene, results_dir):
    summary = results_dir / "cortellis_ibd" / f"{gene}_summary.md"
    if summary.exists():
        content = summary.read_text(errors="ignore")
        return markdown_to_html("\n".join(content.split("\n")[:40]))
    return f"<p>No Cortellis summary available for {gene}.</p>"


# ---------------------------------------------------------------------------
# Scoring auxiliaries
# ---------------------------------------------------------------------------

def build_radar_figure(combo_scores):
    categories = ["Clinical", "Biology", "Safety", "Druggability", "Translation", "Commercial"]
    top = sorted(combo_scores.items(), key=lambda kv: kv[1].get("overall", 0), reverse=True)
    traces = []
    for name, scores in top:
        values = [
            scores.get("clinical", 0),
            scores.get("biology", 0),
            scores.get("safety", 0),
            scores.get("druggability", 0),
            scores.get("translation", 0),
            scores.get("commercial", 0),
        ]
        values.append(values[0])
        traces.append({
            "type": "scatterpolar",
            "r": values,
            "theta": categories + [categories[0]],
            "fill": "toself",
            "name": name,
            "opacity": 0.7,
        })
    layout = {
        "polar": {"radialaxis": {"visible": True, "range": [0, 100]}},
        "showlegend": True,
        "title": "Combination Subscore Radar",
        "height": 520,
        "margin": {"t": 60, "b": 40, "l": 60, "r": 60},
    }
    return {"data": traces, "layout": layout, "config": {"responsive": True}}


def build_translation_html(combo, combo_data, gene_scores, bio_components):
    """Build Translation section HTML for a combo card."""
    genes = combo
    ukbppp_score = bio_components.get("ukbppp", 0.0)
    sig_score = bio_components.get("signature", 0.0)
    translation_score = 0.5 * ukbppp_score + 0.5 * sig_score

    html = '<div class="bar-plot" aria-label="Translation component bars">'
    html += f'<div class="bar" style="--value: {ukbppp_score};"><div class="row"><div><div class="name">UKBPPP</div><div class="meta">weight 0.50</div></div><div class="track" aria-hidden="true"><div class="fill"></div></div><div class="meta" style="text-align:right;"><span class="score">{ukbppp_score:.1f}</span> / 100</div></div></div>'
    html += f'<div class="bar" style="--value: {sig_score};"><div class="row"><div><div class="name">Combo Signature</div><div class="meta">weight 0.50</div></div><div class="track" aria-hidden="true"><div class="fill"></div></div><div class="meta" style="text-align:right;"><span class="score">{sig_score:.1f}</span> / 100</div></div></div>'
    html += '</div>'

    html += '<details open style="margin-top: 14px;"><summary>Per-gene UKBPPP scores</summary>'
    html += '<table class="rank-table score-color-table" style="margin-top: 10px;"><thead><tr><th>Gene</th><th>UKBPPP Score</th></tr></thead><tbody>'
    for g in genes:
        gs = gene_scores.get(g, {})
        gc = gs.get("components", {}).get("biology", {})
        ukb = gc.get("ukbppp", 0.0)
        html += f'<tr><td style="font-weight:850;">{g}</td><td class="scorecell">{ukb:.1f}</td></tr>'
    html += '</tbody></table></details>'

    html += f'<p style="margin-top:12px;"><strong>Combined Translation = 0.5 × UKBPPP ({ukbppp_score:.1f}) + 0.5 × Sig ({sig_score:.1f}) = {translation_score:.1f}</strong></p>'
    return html


def build_commercial_html(combo, commercial_dir):
    """Build Commercial section HTML for a combo card."""
    combo_slug_str = "_".join(combo)
    result_path = Path(commercial_dir) / combo_slug_str / "commercial_result.json"
    if not result_path.exists():
        return "<p class='note warn'>No commercial assessment available for this combination.</p>"

    with open(result_path) as f:
        data = json.load(f)

    score = data.get("commercial_score", 0)
    conf = data.get("confidence", "?")
    comps = data.get("components", {})
    mkt = comps.get("market_opportunity", {})
    comp = comps.get("competitive_profile", {})
    strat = comps.get("strategic_fit", {})
    narrative = data.get("narrative_summary", "")

    conf_color = {"High": "#22c55e", "Medium": "#eab308", "Low": "#f97316"}.get(conf, "#94a3b8")

    html = f'<div style="display:flex;align-items:center;gap:12px;margin-bottom:16px;">'
    html += f'<span style="font-size:2em;font-weight:900;">{score:.1f}</span>'
    html += f'<span style="background:{conf_color};color:#fff;padding:2px 10px;border-radius:12px;font-size:12px;font-weight:700;">{conf} confidence</span>'
    html += '</div>'

    html += '<div class="bar-plot" aria-label="Commercial component bars">'
    for label, comp_data in [("Market Opportunity", mkt), ("Competitive Profile", comp), ("Strategic Fit", strat)]:
        s = comp_data.get("score", 0)
        html += f'<div class="bar" style="--value: {s};"><div class="row"><div><div class="name">{label}</div><div class="meta">{comp_data.get("rationale", "")[:120]}</div></div><div class="track" aria-hidden="true"><div class="fill"></div></div><div class="meta" style="text-align:right;"><span class="score">{s:.0f}</span> / 100</div></div></div>'
    html += '</div>'

    if narrative:
        html += f'<details open style="margin-top:14px;"><summary>Executive Narrative</summary><div class="md"><p>{narrative}</p></div></details>'

    citations = data.get("citations", [])
    if citations:
        html += '<details style="margin-top:10px;"><summary>Citations</summary><ul style="font-size:12px;">'
        for c in citations[:8]:
            if isinstance(c, dict):
                html += f'<li>{c.get("source", "")} — {c.get("relevance", "")}</li>'
            else:
                html += f'<li>{c}</li>'
        html += '</ul></details>'

    return html


def build_executive_summary(combo_scores, top_n=3):
    sorted_combos = sorted(combo_scores.items(), key=lambda kv: kv[1].get("overall", 0), reverse=True)
    top = sorted_combos[:top_n]
    html = (
        "<p><strong>Scoring weights:</strong> Overall = 0.25·Clinical + 0.25·Biology "
        "+ 0.125·Safety + 0.125·Druggability + 0.125·Translation + 0.125·Commercial</p>\n"
        f"<p><strong>Top {top_n} Combinations by Overall Score:</strong></p>\n<ol>\n"
    )
    for name, scores in top:
        html += (
            f"<li><strong>{name}</strong> — Overall: {scores['overall']:.1f} "
            f"(Clinical: {scores['clinical']:.1f}, Biology: {scores['biology']:.1f}, "
            f"Safety: {scores['safety']:.1f}, Druggability: {scores['druggability']:.1f}, "
            f"Translation: {scores.get('translation', 0):.1f}, Commercial: {scores.get('commercial', 0):.1f})</li>\n"
        )
    html += "</ol>\n"
    html += (
        f"<p>Report covers {len(combo_scores)} combinations across 6 scoring dimensions.</p>"
    )
    return html


def build_methodology_html():
    return {
        "overall_html": (
            "<p><strong>Overall Score</strong> = 0.25·Clinical + 0.25·Biology + 0.125·Safety "
            "+ 0.125·Druggability + 0.125·Translation + 0.125·Commercial</p>"
            "<p>Weights sum to 1.0. Each component is scored 0–100.</p>"
            "<p><strong>Translation</strong> = 0.5×UKBPPP + 0.5×Combo Signature (agonist-corrected, "
            "dynamic-max normalized across all combos).</p>"
            "<p><strong>Combination scoring:</strong> combo scores use combo-level data where "
            "available (KG Part2, OFF-X combo results, GSP combo scores), with fallback to "
            "mean-of-members.</p>"
        ),
        "clinical_html": (
            "<p><strong>Clinical Validation</strong> measures the highest development phase "
            "for drugs targeting each gene.</p>"
            "<ul>"
            "<li>Source: Cortellis Drug Discovery Intelligence</li>"
            "<li>Scoring: Launched=100, Phase 3=80, Phase 2=60, Phase 1=40, Preclinical=20, Discovery=10</li>"
            "<li>Combo: mean of member-gene clinical scores</li>"
            "</ul>"
        ),
        "disease_html": (
            "<p><strong>Biology</strong> = 0.20·DEG + 0.20·Signature + 0.12·BioBridge + 0.12·ULTRA + 0.06·PrimeKG + 0.15·GSP + 0.15·UKBPPP</p>"
            "<ul>"
            "<li><strong>DEG (20%):</strong> Mean target gene total_score from target_score_table.csv, agonist-negated, dynamic-max normalized across all combos.</li>"
            "<li><strong>Signature (20%):</strong> GSEA NES-based signature_score_table.csv (one row per signature), agonist-negated, dynamic-max normalized across all combos.</li>"
            "<li><strong>BioBridge (12%):</strong> Multimodal KG embedding percentile × 100.</li>"
            "<li><strong>ULTRA (12%):</strong> Foundation model link-prediction percentile × 100.</li>"
            "<li><strong>PrimeKG (6%):</strong> KG connectivity × 100.</li>"
            "<li><strong>GSP (15%):</strong> GWAS + Mendelian + burden. High=100, Med=50, Low=25, None=0.</li>"
            "<li><strong>UKBPPP (15%):</strong> UKB Pharma Proteomics Project. FDR-significant model count scoring (0-100). Not on panel = 0.</li>"
            "</ul>"
        ),
        "opportunity_html": (
            "<p><strong>Druggability</strong> measures predicted tractability for drug development.</p>"
            "<ul>"
            "<li>Source: DrugnomeAI PU learning model</li>"
            "<li>Scoring: composite_score × 100</li>"
            "<li>Combo: mean of member-gene druggability scores</li>"
            "</ul>"
        ),
        "novelty_html": (
            "<p><strong>Translation</strong> = 0.5 × UKBPPP + 0.5 × Combo Signature (normalized)</p>"
            "<ul>"
            "<li>UKBPPP (50%): UKB Pharma Proteomics Project (K50/K51 disease models, FDR-significant, 0-100)</li>"
            "<li>Combo Signature (50%): Agonist-corrected signature score, normalized by max across all combos (0-100)</li>"
            "<li>Agonist genes (GLP2R): signature negated before normalization</li>"
            "<li>Genes not on UKBPPP panel: UKBPPP component = 0</li>"
            "<li>Combo: 0.5 × mean-member-UKBPPP + 0.5 × combo-sig-normalized</li>"
            "</ul>"
        ),
        "safety_html": (
            "<p><strong>Safety</strong> uses OFF-X target safety evidence.</p>"
            "<ul>"
            "<li>Raw: average_score (negative = more adverse events linked)</li>"
            "<li>Transform: Safety = 50 + (avg_score × 10), clamped [0, 100]</li>"
            "<li>Combo: use combo_results avg_score if available, else mean members</li>"
            "</ul>"
        ),
        "commercial_html": (
            "<p><strong>Commercial</strong> = 0.40 × Market_Opportunity + 0.40 × Competitive_Profile + 0.20 × Strategic_Fit</p>"
            "<ul>"
            "<li><strong>Market Opportunity (40%):</strong> IBD market size ($25B+ global), growth trajectory, "
            "patient population, unmet need addressable by this target/combo, reimbursement landscape.</li>"
            "<li><strong>Competitive Profile (40%):</strong> Existing marketed therapies and pipeline programs "
            "targeting these mechanisms. Novel targets (0 active drugs) = 80-95; highly crowded = 25-55. "
            "CI pipeline drug counts used as quantitative grounding.</li>"
            "<li><strong>Strategic Fit (20%):</strong> GI/immunology core = 80-100, adjacent autoimmune = 60-79, "
            "distant TA = 20-59. Scored modality-agnostic on TA relevance.</li>"
            "</ul>"
            "<p><strong>Combo-level:</strong> Deep web research per combo evaluating the combination as a product.</p>"
            "<p><strong>Gene-level:</strong> Individual target commercial assessment via dedicated deep research. "
            "Fallback: mean of combo scores containing that gene.</p>"
            "<p><strong>Source:</strong> On-the-fly deep web research (WebSearch + WebFetch) grounded in "
            "CI pipeline data + Cortellis context. Scores calibrated to differentiate within the indication.</p>"
        ),
    }


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def generate_report(output_path=None):
    config = load_config()
    combos = config["combos"]
    genes = config["genes_unique"]

    print("Loading data from all sources...")
    all_data = load_all_data(
        genes=genes,
        combos=combos,
        base_dir=str(BASE_DIR),
        indication="ibd",
    )

    print("Calculating scores...")
    scores = calculate_overall_scores(
        all_data=all_data,
        combos=combos,
        genes=genes,
        gene_approaches=GENE_APPROACHES,
    )
    combo_scores = scores["combos"]
    gene_scores = scores["genes"]

    print("Extracting Plotly bundle from target_signature exports...")
    plotly_bundle = extract_plotly_bundle()
    print(f"  Plotly bundle: {len(plotly_bundle) / (1024*1024):.2f} MB")

    print("Collecting combo-level Plotly figures...")
    plot_figs = {"radar::rankings": build_radar_figure(combo_scores)}
    persample_fig_keys = {}  # anchor -> list of "<study>::<stem>" fig keys
    archs4_fig_keys = {}  # anchor -> list of (label, fig_key)
    cellxgene_fig_keys = {}  # anchor -> list of (label, fig_key)

    # Results dir for narrative/markdown content (still symlinked in results/).
    results_dir = BASE_DIR / "results"

    for combo in combos:
        plot_figs.update(collect_combo_level_figs(combo))
        anchor = combo_anchor(combo)
        ps_keys = []
        for raw_key, fig in build_persample_figures(combo):
            fig_key = f"{anchor}::ps::{raw_key}"
            plot_figs[fig_key] = fig
            ps_keys.append((raw_key, fig_key))
        persample_fig_keys[anchor] = ps_keys

        # ARCHS4 figures
        archs4_pairs = []
        for raw_key, fig in build_archs4_figures(combo):
            fig_key = f"{anchor}::archs4::{raw_key}"
            plot_figs[fig_key] = fig
            archs4_pairs.append((raw_key, fig_key))
        archs4_fig_keys[anchor] = archs4_pairs

        # CellXGene figures
        cellxgene_pairs = []
        for raw_key, fig in build_cellxgene_figures(combo):
            fig_key = f"{anchor}::cellxgene::{raw_key}"
            plot_figs[fig_key] = fig
            cellxgene_pairs.append((raw_key, fig_key))
        cellxgene_fig_keys[anchor] = cellxgene_pairs

    # ----------- ranking + card structures -----------
    print("Building template context...")
    sorted_combos = sorted(
        [(c, combo_scores.get(format_combo_name(c), {})) for c in combos],
        key=lambda x: x[1].get("overall", 0),
        reverse=True,
    )
    ranking_rows = []
    for rank, (combo, sd) in enumerate(sorted_combos, 1):
        ranking_rows.append({
            "rank": rank,
            "name": format_combo_name(combo),
            "anchor": combo_anchor(combo),
            "genes": ", ".join(combo),
            "overall": f"{sd.get('overall', 0):.1f}",
            "clinical": f"{sd.get('clinical', 0):.1f}",
            "disease": f"{sd.get('biology', 0):.1f}",
            "opportunity": f"{sd.get('druggability', 0):.1f}",
            "novelty": f"{sd.get('translation', 0):.1f}",
            "commercial": f"{sd.get('commercial', 0):.1f}",
            "safety": f"{sd.get('safety', 0):.1f}",
        })

    combo_cards = []
    plot_targets = {}
    for combo, _ in sorted_combos:
        name = format_combo_name(combo)
        anchor = combo_anchor(combo)
        sd = combo_scores.get(name, {})
        bio = sd.get("components", {}).get("biology", {})

        disease_components = [
            {"label": "DEG Evidence", "weight": "0.20", "value": f"{bio.get('deg', 50):.1f}"},
            {"label": "Signature",    "weight": "0.20", "value": f"{bio.get('signature', 50):.1f}"},
            {"label": "BioBridge",    "weight": "0.12", "value": f"{bio.get('biobridge', 50):.1f}"},
            {"label": "ULTRA",        "weight": "0.12", "value": f"{bio.get('ultra', 50):.1f}"},
            {"label": "PrimeKG",      "weight": "0.06", "value": f"{bio.get('primekg', 50):.1f}"},
            {"label": "GSP Genetics", "weight": "0.15", "value": f"{bio.get('gsp', 0):.1f}"},
            {"label": "UKBPPP",       "weight": "0.15", "value": f"{bio.get('ukbppp', 0):.1f}"},
        ]

        gene_rows = []
        disease_gene_rows = []
        for g in combo:
            gs = gene_scores.get(g, {})
            gc = gs.get("components", {}).get("biology", {})
            gene_rows.append({
                "gene": g,
                "overall": f"{gs.get('overall', 0):.1f}",
                "clinical": f"{gs.get('clinical', 0):.1f}",
                "disease": f"{gs.get('biology', 0):.1f}",
                "opportunity": f"{gs.get('druggability', 0):.1f}",
                "novelty": f"{gs.get('translation', 0):.1f}",
                "commercial": f"{gs.get('commercial', 0):.1f}",
                "safety": f"{gs.get('safety', 0):.1f}",
            })
            disease_gene_rows.append({
                "gene": g,
                "disease": f"{gs.get('biology', 0):.1f}",
                "deg": f"{gc.get('deg', 50):.1f}",
                "biobridge": f"{gc.get('biobridge', 50):.1f}",
                "ultra": f"{gc.get('ultra', 50):.1f}",
                "primekg": f"{gc.get('primekg', 50):.1f}",
            })

        # Track which combo-level figs we have and persample studies present.
        comparison_sig_key = f"{anchor}::comparison_signature"
        target_sig_key = f"{anchor}::target_signature"

        ps_pairs = persample_fig_keys.get(anchor, [])
        archs4_pairs = archs4_fig_keys.get(anchor, [])
        cellxgene_pairs = cellxgene_fig_keys.get(anchor, [])

        plot_targets[anchor] = {
            "comparisonSignatureKey": comparison_sig_key if comparison_sig_key in plot_figs else "",
            "targetSignatureKey": target_sig_key if target_sig_key in plot_figs else "",
            "persamplePlots": [{"label": label, "figKey": fk} for label, fk in ps_pairs],
            "archs4Plots": [{"label": label, "figKey": fk} for label, fk in archs4_pairs],
            "cellxgenePlots": [{"label": label, "figKey": fk} for label, fk in cellxgene_pairs],
        }

        combo_cards.append({
            "name": name,
            "anchor": anchor,
            "long_genes": ", ".join(combo),
            "scores": {
                "overall": f"{sd.get('overall', 0):.1f}",
                "clinical": f"{sd.get('clinical', 0):.1f}",
                "disease": f"{sd.get('biology', 0):.1f}",
                "opportunity": f"{sd.get('druggability', 0):.1f}",
                "novelty": f"{sd.get('translation', 0):.1f}",
                "commercial": f"{sd.get('commercial', 0):.1f}",
                "safety": f"{sd.get('safety', 0):.1f}",
            },
            "disease_components": disease_components,
            "gene_rows": gene_rows,
            "disease_gene_rows": disease_gene_rows,
            "overview_html": f"<p>Combination of {name} targeting IBD through complementary mechanisms.</p>",
            "disease_interpretation_html": "<p>Biology evidence from DEG, BioBridge, ULTRA, PrimeKG, and GSP genetics analyses.</p>",
            "bulk_interpretation_html": "<p>Combo-level DEG signature heatmap (left) and comparison-level signature (right) drawn from the omicsoft pipeline.</p>",
            "persample_plots": [{"label": label, "fig_key": fk} for label, fk in ps_pairs],
            "archs4_plots": [{"label": label, "fig_key": fk} for label, fk in archs4_pairs],
            "cellxgene_plots": [{"label": label, "fig_key": fk} for label, fk in cellxgene_pairs],
            "pathway_summary_html": load_pathway_narrative(combo, results_dir),
            "ppi_html": load_ppi_narrative(combo, results_dir),
            "translation_html": build_translation_html(combo, all_data.get("per_combo", {}).get(name, {}), gene_scores, bio),
            "commercial_html": build_commercial_html(combo, str(BASE_DIR / "test" / "commercial")),
        })

    # ----------- single-gene cards -----------
    gene_rows_all = []
    gene_cards_list = []
    sorted_genes = sorted(genes, key=lambda g: gene_scores.get(g, {}).get("overall", 0), reverse=True)
    for g in sorted_genes:
        gs = gene_scores.get(g, {})
        gc = gs.get("components", {}).get("biology", {})
        gene_rows_all.append({
            "gene": g,
            "overall": f"{gs.get('overall', 0):.1f}",
            "clinical": f"{gs.get('clinical', 0):.1f}",
            "disease": f"{gs.get('biology', 0):.1f}",
            "opportunity": f"{gs.get('druggability', 0):.1f}",
            "novelty": f"{gs.get('translation', 0):.1f}",
            "safety": f"{gs.get('safety', 0):.1f}",
        })
        components = [
            {"label": "DEG Evidence", "weight": "0.20", "value": f"{gc.get('deg', 50):.1f}"},
            {"label": "Signature",    "weight": "0.20", "value": f"{gc.get('signature', 50):.1f}"},
            {"label": "BioBridge",    "weight": "0.12", "value": f"{gc.get('biobridge', 50):.1f}"},
            {"label": "ULTRA",        "weight": "0.12", "value": f"{gc.get('ultra', 50):.1f}"},
            {"label": "PrimeKG",      "weight": "0.06", "value": f"{gc.get('primekg', 50):.1f}"},
            {"label": "GSP Genetics", "weight": "0.15", "value": f"{gc.get('gsp', 0):.1f}"},
            {"label": "UKBPPP",       "weight": "0.15", "value": f"{gc.get('ukbppp', 0):.1f}"},
        ]
        gene_cards_list.append({
            "name": g,
            "anchor": gene_anchor(g),
            "long_name": g,
            "scores": {
                "overall": f"{gs.get('overall', 0):.1f}",
                "clinical": f"{gs.get('clinical', 0):.1f}",
                "disease": f"{gs.get('biology', 0):.1f}",
                "opportunity": f"{gs.get('druggability', 0):.1f}",
                "novelty": f"{gs.get('translation', 0):.1f}",
                "commercial": f"{gs.get('commercial', 0):.1f}",
                "safety": f"{gs.get('safety', 0):.1f}",
            },
            "disease_components": components,
            "overview_html": load_gene_overview(g, results_dir),
            "disease_interpretation_html": "<p>Biology evidence from KG and DEG analyses.</p>",
            "pathway_html": load_pathway_narrative([g], results_dir),
        })

    # ----------- CI dashboard embedding -----------
    ci_dash_path = BASE_DIR / "results" / "ci_ibd" / "ibd_dashboard.html"
    ci_dashboard_html = ""
    if ci_dash_path.exists():
        ci_dashboard_html = ci_dash_path.read_text(errors="ignore")
        print(f"  CI Dashboard: {len(ci_dashboard_html) / 1024:.0f} KB")

    # ----------- template render -----------
    context = {
        "title": "IBD Combination Prioritization Report",
        "nav_title": "IBD Combo Prioritization",
        "subtitle": f"Systematic prioritization of {len(combos)} target combinations for Inflammatory Bowel Disease",
        "generation_date": datetime.now().strftime("%Y-%m-%d"),
        "builders": "Xinghao Zhang",
        "build_id": f"IBD-{datetime.now().strftime('%Y%m%d')}",
        "executive_html": build_executive_summary(combo_scores),
        "ranking_rows": ranking_rows,
        "combos": combo_cards,
        "gene_rows_all": gene_rows_all,
        "gene_cards": gene_cards_list,
        "ci_dashboard_available": ci_dashboard_html != "",
        "ci_dashboard_html_escaped": json.dumps(ci_dashboard_html).replace("</script>", r"<\/script>") if ci_dashboard_html else '""',
        "methodology": build_methodology_html(),
        "plotly_bundle_js": plotly_bundle,
        "plot_figs_js": json.dumps(plot_figs),
        "plot_targets_json": json.dumps(plot_targets),
    }

    print("Rendering template...")
    template_content = TEMPLATE_PATH.read_text()
    env = jinja2.Environment(
        loader=jinja2.BaseLoader(),
        autoescape=False,
        undefined=jinja2.Undefined,
    )
    template = env.from_string(template_content)
    html_output = template.render(**context)

    if output_path is None:
        output_path = OUTPUT_DIR / "IBD_Combo_Prioritization_Report_offline.html"
    else:
        output_path = Path(output_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html_output)
    size_mb = output_path.stat().st_size / (1024 * 1024)
    print(f"Report generated: {output_path}")
    print(f"File size: {size_mb:.1f} MB")
    return output_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate IBD Combo Prioritization Report")
    parser.add_argument("--output", type=str, help="Output HTML path")
    args = parser.parse_args()
    generate_report(args.output)
