#!/usr/bin/env python3
"""
Omicsoft Bulk DEG Analysis Script
Customizable differential gene expression analysis for h5ad files

Usage:
    python deg_analysis.py --file <path> --target <gene> --diseases <disease1,disease2> [options]
"""

import os
import sys
import argparse
from datetime import datetime
import tempfile
import subprocess

import anndata
import scanpy as sc
import pandas as pd
import numpy as np
from scipy import sparse
from scipy.cluster.hierarchy import linkage, leaves_list
from scipy.spatial.distance import pdist

import gseapy as gp
from tqdm import tqdm

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
import plotly.figure_factory as ff
from plotly.colors import qualitative

import random
import json
import glob as glob_module
from concurrent.futures import ProcessPoolExecutor, as_completed
import multiprocessing

# Set random seed for reproducibility
random.seed(42)


def export_json_file(df, filepath):
    """
    Export DataFrame to JSON file alongside CSV export.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame to export
    filepath : str
        Path to JSON file (should end with .json)
    """
    # Convert DataFrame to list of records (preserves column types better)
    records = df.to_dict(orient='records')

    with open(filepath, 'w') as f:
        json.dump(records, f, indent=2, default=str)

    print(f"Saved JSON export to {filepath}")


def load_combined_pathways():
    """
    Load pathway gene sets from pathwaydb-query skill's combined_pathways.csv.

    This function loads the universal pathway database generated by /pathwaydb-query skill,
    which contains pathways from KEGG, Reactome, and MSigDB.

    Returns
    -------
    tuple
        (pathway_gene_sets, pathway_metadata) or (None, None) if file not found
        - pathway_gene_sets: dict of {pathway_name: [gene_list]}
        - pathway_metadata: DataFrame with Pathway, Database, Pathway_ID columns
    """
    default_path = os.path.expanduser(
        '~/.claude/skills/pathwaydb-query/data/combined_pathways.csv'
    )

    if not os.path.exists(default_path):
        print(f"ERROR: {default_path} not found")
        print("Run /pathwaydb-query skill first to generate combined_pathways.csv")
        return None, None

    print(f"Loading combined pathways from: {default_path}")
    df = pd.read_csv(default_path)
    print(f"  Loaded {len(df)} pathway entries")

    # Expected columns: Pathway, Database, Pathway_ID, Gene_Members
    required_cols = ['Pathway', 'Database', 'Gene_Members']
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        print(f"ERROR: Missing required columns: {missing_cols}")
        return None, None

    # Build gene sets from Gene_Members column
    pathway_gene_sets = {}

    for _, row in df.iterrows():
        pathway_name = row['Pathway']
        gene_members_str = str(row.get('Gene_Members', ''))

        if gene_members_str and gene_members_str != 'nan':
            genes = [g.strip() for g in gene_members_str.split(';') if g.strip()]
        else:
            continue

        if len(genes) >= 3:  # Skip pathways with too few genes
            pathway_gene_sets[pathway_name] = genes

    pathway_metadata = df[['Pathway', 'Database', 'Pathway_ID']].copy()

    print(f"  Created {len(pathway_gene_sets)} pathway gene sets (min 3 genes)")
    print(f"  Databases: {df['Database'].unique().tolist()}")

    return pathway_gene_sets, pathway_metadata


def run_pathwaydb_gsea_new(enrich_df, pathway_gene_sets, pathway_metadata,
                           indication, workdir='.', n_workers=16, export_json=False):
    """
    Run GSEA using combined pathways - indication-centric output.

    This is the new implementation that uses the universal pathway database
    from /pathwaydb-query skill, independent of any target gene.

    Outputs are saved to a timestamped subdirectory in the working directory:
    {workdir}/{indication}_pathwaydb_{YYYYMMDD}/

    Parameters
    ----------
    enrich_df : pd.DataFrame
        DataFrame with rank_score column (indexed by Gene)
    pathway_gene_sets : dict
        Dictionary of {pathway_name: [gene_list]}
    pathway_metadata : pd.DataFrame
        DataFrame with Pathway, Database, Pathway_ID columns
    indication : str
        Indication name for output file naming (e.g., "IBD", "Fibrosis")
    workdir : str
        Working directory for output (default: current directory)
    n_workers : int
        Number of parallel workers for GSEA

    Returns
    -------
    pd.DataFrame or None
        GSEA results with pathway metadata, or None if no results
    """
    print(f"\n[PathwayDB GSEA] Running GSEA with {len(pathway_gene_sets)} pathway gene sets...")

    res_list = []

    groupby_keys = ['study', 'comparison', 'comparison_category']
    for c, df in tqdm(enrich_df.groupby(groupby_keys),
                      desc="Running PathwayDB GSEA"):
        study_id = str(c[0])
        comparison_val = str(c[1])
        study_comp = f"{study_id}: {comparison_val}"
        comp_category = c[2]

        # Get all metadata from first row
        metadata = get_group_metadata(df.reset_index(), groupby_keys)

        rank_series = df['rank_score'][df['rank_score'] != 0].sort_values(ascending=False)
        if len(rank_series) < 100:
            continue

        try:
            res = gp.prerank(
                rnk=rank_series,
                gene_sets=pathway_gene_sets,
                permutation_num=1000,
                min_size=3,
                max_size=20000,
                threads=n_workers,
                seed=42,
                outdir=None,
                verbose=False
            )
            # Assign split columns + all metadata
            res_df = res.res2d.assign(
                study=study_id,
                comparison=comparison_val,
                study_comparison=study_comp,
                comparison_category=comp_category,
                **metadata
            )
            res_list.append(res_df)
        except Exception as e:
            print(f'  skip {study_comp}: {e}')

    if not res_list:
        print("No PathwayDB GSEA results generated")
        return None

    result_df = pd.concat(res_list, ignore_index=True)

    # Merge with pathway metadata
    result_df = result_df.merge(
        pathway_metadata,
        left_on='Term',
        right_on='Pathway',
        how='left'
    )
    result_df = result_df.drop(columns=['Pathway'], errors='ignore')

    # Reorder columns: GSEA results first, then priority metadata, then rest
    gsea_cols = ['Term', 'Database', 'Pathway_ID', 'NES', 'NOM p-val',
                 'FDR q-val', 'FWER p-val', 'Tag %', 'Gene %', 'Lead_genes']
    priority_meta = ['study', 'comparison', 'study_comparison', 'tissue', 'disease',
                     'disease_category', 'comparison_category', 'case_treatment',
                     'control_treatment', 'case_treatment_status', 'control_treatment_status']

    existing_gsea = [c for c in gsea_cols if c in result_df.columns]
    existing_priority = [c for c in priority_meta if c in result_df.columns]
    other_cols = [c for c in result_df.columns if c not in gsea_cols + priority_meta]
    result_df = result_df[existing_gsea + existing_priority + other_cols]

    # Create timestamped output directory in working directory
    timestamp = datetime.now().strftime('%Y%m%d')  # YYYYMMDD format, no hour/minute
    pathwaydb_dir = f'{workdir}/{indication}_pathwaydb_{timestamp}'
    os.makedirs(pathwaydb_dir, exist_ok=True)

    # Save outputs to timestamped directory (Parquet by default)
    output_file = f'{pathwaydb_dir}/{indication}_pathwaydb_gsea.parquet'
    result_df.to_parquet(output_file, index=False, engine='pyarrow')
    print(f"Saved: {output_file}")
    if export_json:
        json_file = f'{pathwaydb_dir}/{indication}_pathwaydb_gsea.json'
        export_json_file(result_df, json_file)
        print(f"Saved: {json_file}")

    # Print summary
    result_df['FDR q-val'] = pd.to_numeric(result_df['FDR q-val'], errors='coerce')
    sig_results = result_df[result_df['FDR q-val'] < 0.05]

    print(f"\n  PathwayDB GSEA Summary:")
    print(f"    Total pathway-comparison tests: {len(result_df)}")
    print(f"    Significant (FDR < 0.05): {len(sig_results)}")
    if len(sig_results) > 0:
        print(f"    Top enriched pathways:")
        top_pathways = sig_results.nsmallest(5, 'FDR q-val')[['Term', 'Database', 'NES', 'FDR q-val']]
        print(top_pathways.to_string(index=False))

    return result_df

# Check if SOMA support is available
try:
    from soma_loader import (
        SOMA_AVAILABLE,
        is_soma_uri,
        try_soma_open,
        detect_soma_structure,
        load_soma_deg,
        get_soma_context,
        SOMAStructureType
    )
except ImportError:
    SOMA_AVAILABLE = False

# Global variable to hold current filters for SOMA loading
_current_filters = None


def is_s3_uri(path):
    """Check if path is an S3 URI"""
    return isinstance(path, str) and path.startswith('s3://')


def validate_s3_access(s3_uri):
    """
    Validate access to S3 object

    Parameters
    ----------
    s3_uri : str
        S3 URI in format s3://bucket/key

    Returns
    -------
    bool
        True if accessible, False otherwise
    """
    try:
        import boto3
        from botocore.exceptions import ClientError, NoCredentialsError

        # Parse S3 URI
        if not s3_uri.startswith('s3://'):
            return False

        parts = s3_uri[5:].split('/', 1)
        if len(parts) != 2:
            print(f"Invalid S3 URI format: {s3_uri}")
            return False

        bucket, key = parts

        # Check access
        s3_client = boto3.client('s3')
        s3_client.head_object(Bucket=bucket, Key=key)
        print(f"✓ S3 access validated: {s3_uri}")
        return True

    except NoCredentialsError:
        print(f"✗ No AWS credentials found. Cannot access S3 URI: {s3_uri}")
        return False
    except ClientError as e:
        error_code = e.response['Error']['Code']
        if error_code == '404':
            print(f"✗ S3 object not found: {s3_uri}")
        elif error_code == '403':
            print(f"✗ Access denied to S3 object: {s3_uri}")
        else:
            print(f"✗ Error accessing S3 object: {e}")
        return False
    except Exception as e:
        print(f"✗ Unexpected error validating S3 access: {e}")
        return False


def load_data(file_path, filters=None):
    """
    Load data from local path, S3 URI, or SOMA experiment with auto-detection.

    Auto-detection logic:
    - S3 URIs not ending in .h5ad: Try SOMA first, fall back to h5ad
    - S3 URIs ending in .h5ad: Load as h5ad via s3fs
    - Local paths: Load as h5ad

    Parameters
    ----------
    file_path : str
        Local file path, S3 URI (s3://bucket/key), or SOMA experiment URI
    filters : dict, optional
        Filter configuration for SOMA loading. If provided, filters are applied
        during SOMA load (server-side filtering). Ignored for h5ad files.

    Returns
    -------
    anndata.AnnData
        Loaded AnnData object

    Notes
    -----
    For h5ad files named with pattern *_deg.h5ad and containing a corresponding
    *_expr key in uns, that key will be deleted to reduce memory usage.

    For SOMA experiments, the function detects whether it's DEG-style (log2fc/padj)
    or expression-style and loads accordingly.
    """
    global _current_filters
    _current_filters = filters

    # Check if this could be a SOMA URI
    if is_s3_uri(file_path) and SOMA_AVAILABLE:
        # S3 path that doesn't end in .h5ad - try SOMA first
        if not file_path.lower().endswith('.h5ad'):
            print(f"Detected S3 URI (non-h5ad): {file_path}")
            print("Attempting to open as SOMA experiment...")

            try:
                # Get context for S3 access (use AWS_DEFAULT_REGION env var or default to us-east-1)
                region = os.environ.get("AWS_DEFAULT_REGION", "us-east-1")
                context = get_soma_context(region=region)

                # Try to open as SOMA
                success, exp = try_soma_open(file_path, context)

                if success:
                    exp.close()  # Close the test open

                    # Detect structure type
                    structure_type = detect_soma_structure(file_path, context)
                    print(f"Detected SOMA experiment (structure: {structure_type.value})")

                    # Load via SOMA loader
                    adata = load_soma_deg(
                        file_path,
                        filters=filters,
                        context=context
                    )

                    print(f"✓ Successfully loaded SOMA experiment")
                    return adata
                else:
                    print("SOMA open failed, falling back to h5ad loading...")

            except Exception as e:
                print(f"SOMA loading failed: {e}")
                print("Falling back to h5ad loading...")

    # Standard h5ad loading path
    return _load_h5ad_internal(file_path)


def _load_h5ad_internal(file_path):
    """
    Internal function to load h5ad file from local path or S3 URI.

    Parameters
    ----------
    file_path : str
        Local file path or S3 URI (s3://bucket/key)

    Returns
    -------
    anndata.AnnData
        Loaded AnnData object with expression data removed from uns
    """
    if is_s3_uri(file_path):
        print(f"Detected S3 URI: {file_path}")

        # Validate S3 access
        if not validate_s3_access(file_path):
            raise ValueError(f"Cannot access S3 object: {file_path}")

        # Load directly from S3 using s3fs
        print("Loading h5ad file directly from S3...")
        try:
            import s3fs
            fs = s3fs.S3FileSystem()
            with fs.open(file_path, 'rb') as f:
                adata = sc.read_h5ad(f)
            print("✓ Successfully loaded from S3")
        except ImportError:
            raise ImportError(
                "s3fs package is required to read from S3. "
                "Install it with: pip install s3fs"
            )
    else:
        print(f"Detected local path: {file_path}")

        # Validate local file exists
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Local file not found: {file_path}")

        print("Loading h5ad file from local path...")
        adata = sc.read_h5ad(file_path)
        print("✓ Successfully loaded from local path")

    # Clean up expression data from uns if present
    # Extract base name from file path (works for both local and S3)
    if is_s3_uri(file_path):
        # For S3 URIs, get the last part after the final /
        base_name = file_path.split('/')[-1]
    else:
        # For local paths, get the filename
        base_name = os.path.basename(file_path)

    # Remove .h5ad extension
    base_name = base_name.replace('.h5ad', '')

    # Check if file ends with _deg and construct potential expr key
    if base_name.endswith('_deg'):
        potential_expr_key = base_name.replace('_deg', '_expr')

        # Check if this key exists in uns
        if potential_expr_key in adata.uns:
            print(f"\nℹ Found expression data in uns['{potential_expr_key}']")
            print(f"  Removing to reduce memory usage and focus on DEG analysis...")
            del adata.uns[potential_expr_key]
            print(f"✓ Removed uns['{potential_expr_key}']")
        else:
            print(f"\nℹ No expression data found in uns (checked for '{potential_expr_key}')")

    return adata


# Backward compatibility alias
def load_h5ad(file_path):
    """
    Load h5ad file from local path or S3 URI.

    This is a backward compatibility alias for load_data().
    For new code, use load_data() which supports SOMA auto-detection.

    Parameters
    ----------
    file_path : str
        Local file path or S3 URI (s3://bucket/key)

    Returns
    -------
    anndata.AnnData
        Loaded AnnData object
    """
    return load_data(file_path, filters=None)


def ad2long_df(adata, var_name='Gene', padj_col='padj'):
    """Convert AnnData to long-format DataFrame"""
    df_list = []
    adata.obs.index.name = 'index'
    id_vars = [adata.obs.index.name]

    for k, v in adata.layers.items():
        df = pd.DataFrame(
            index=adata.obs_names,
            columns=adata.var_names,
            data=v.toarray() if isinstance(v, sparse._csr.csr_matrix) else v,
        ).reset_index()

        df_long = pd.melt(
            df,
            id_vars=id_vars,
            value_vars=[col for col in df.columns if col not in id_vars],
            var_name=var_name,
            value_name=k
        ).set_index(id_vars[0])

        df_list.append(df_long)

    concat_df = pd.concat(df_list, axis=1)
    concat_df = concat_df.loc[:, ~concat_df.columns.duplicated()]

    # Replace zero with smallest nonzero value
    concat_df[padj_col] = concat_df[padj_col].replace(
        0,
        min(concat_df[padj_col][concat_df[padj_col] != 0]) / 10
    )

    concat_df['-logpadj'] = -np.log(concat_df[padj_col])
    concat_df['trans_logpadj'] = concat_df['-logpadj'].apply(lambda x: np.log2(x + 1))

    meta_df = pd.merge(concat_df, adata.obs, left_index=True, right_index=True, how='outer')

    return meta_df


def get_group_metadata(df, groupby_keys):
    """
    Extract all metadata columns from first row of a grouped DataFrame.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame for a single group from groupby
    groupby_keys : list
        Columns used for groupby (excluded from metadata)

    Returns
    -------
    dict
        All metadata columns (excluding groupby keys and analysis columns)
    """
    # Columns that are not metadata (analysis/computed columns)
    exclude_cols = {'Gene', 'padj', 'log2fc', 'rank_score', '-logpadj', 'trans_logpadj'}
    exclude_cols.update(groupby_keys)

    # Get first row's metadata
    first_row = df.iloc[0]
    metadata = {}
    for col in df.columns:
        if col not in exclude_cols:
            metadata[col] = first_row[col]

    return metadata


def lfc_heatmap_traces(
    adata,
    geneset,
    fig_title,
    lfc="log2fc",
    padj="padj",
    lfc_limit=0,
    padj_limit=0.05,
):
    """
    Create a clustered annotated heatmap for the given anndata object and geneset,
    and return its traces, its layout annotations, and the title.
    No plotting or saving is done here; this is meant to be used in a combined
    figure (e.g., with a dropdown).
    """

    # Use the lfc layer as X and subset to genes in geneset present in adata
    adata = adata.copy()  # avoid mutating original
    adata.X = adata.layers[lfc].copy()
    adata = adata[:, [gene for gene in sorted(geneset) if gene in adata.var_names]]

    # Subset samples with any lfc beyond lfc_limit
    X_dense = adata.X.toarray()
    include_comp = adata.obs_names[(np.abs(X_dense) > lfc_limit).any(axis=1)]
    include_gene = adata.var_names[(np.abs(X_dense) > lfc_limit).any(axis=0)]
    adata = adata[include_comp, include_gene]

    # If nothing survives filtering, just return empty
    if adata.n_obs == 0 or adata.n_vars == 0:
        return [], [], fig_title

    lfc_df = adata.to_df()
    padj_matrix = adata.layers[padj].toarray()
    annotations = np.where(padj_matrix < padj_limit, "*", "")

    # Custom y-axis labels: {study}_{disease}_{comparison}
    y_labels = []
    for idx in lfc_df.index:
        study = adata.obs.loc[idx, "study"]
        disease = adata.obs.loc[idx, "disease_category"]
        comparison = adata.obs.loc[idx, "comparison"]
        y_labels.append(f"{study}_{disease}_{comparison}")

    n_rows, n_cols = lfc_df.shape

    # --- Hierarchical clustering: rows (comparisons) ---
    if n_rows > 1:
        row_linkage = linkage(
            pdist(lfc_df.values, metric="euclidean"),
            method="average",
        )
        row_order = leaves_list(row_linkage)
    else:
        row_order = np.arange(n_rows)

    # --- Hierarchical clustering: columns (genes) ---
    if n_cols > 1:
        col_linkage = linkage(
            pdist(lfc_df.values.T, metric="euclidean"),
            method="average",
        )
        col_order = leaves_list(col_linkage)
    else:
        col_order = np.arange(n_cols)

    # Reorder matrix, annotations, and labels according to clustering
    lfc_df = lfc_df.iloc[row_order, :]
    lfc_df = lfc_df.iloc[:, col_order]

    annotations = annotations[row_order, :][:, col_order]
    y_labels = [y_labels[i] for i in row_order]
    x_labels = list(lfc_df.columns)

    num_x_elements = len(x_labels)
    num_y_elements = len(y_labels)
    plot_width = 50 * num_x_elements
    plot_height = 200 + 30 * num_y_elements

    fig_heatmap = ff.create_annotated_heatmap(
        z=lfc_df.values,
        x=x_labels,
        y=y_labels,
        annotation_text=annotations,
        colorscale="RdBu_r",
        zmid=0,
        hoverinfo="z",
        showscale=True,
    )

    fig_heatmap.update_layout(
        title=fig_title,
        xaxis_title="Genes",
        yaxis_title="Samples",
        xaxis=dict(tickmode="linear"),
        yaxis=dict(tickmode="linear"),
        width=plot_width,
        height=plot_height,
    )

    # Make "*" green
    for annot in fig_heatmap.layout.annotations:
        if annot.text == "*":
            annot.font.color = "green"
            annot.font.size = 20

    # Return traces + annotations + title (for combined dropdown figure)
    return fig_heatmap.data, fig_heatmap.layout.annotations, fig_heatmap.layout.title.text


def create_enhanced_gsea_summary(res_deg_score, signature_set, target_genes=None, fdr_threshold=0.05, output_dir='.', output_filename='gsea_enhanced_summary.csv'):
    """
    Create enhanced GSEA summary table with significance counts, NES grouping, and leading edge annotation

    Parameters
    ----------
    res_deg_score : pd.DataFrame
        GSEA results dataframe with columns: Term, NES, FDR q-val, Lead_genes, study
    signature_set : dict
        Dictionary of signature names to gene lists
    target_genes : list, optional
        List of target genes to track in leading edge (if None, uses all signature genes)
    fdr_threshold : float
        FDR q-value threshold for significance (default: 0.05)
    output_dir : str
        Output directory path
    output_filename : str
        Name of output CSV file

    Returns
    -------
    pd.DataFrame
        Enhanced summary table
    """
    print(f"\nCreating enhanced GSEA summary (FDR < {fdr_threshold})...")

    # Count total comparisons (unique studies in results)
    total_comparisons = res_deg_score['study'].nunique()
    print(f"Total comparisons analyzed: {total_comparisons}")

    # Get genes to track in leading edge
    if target_genes is not None:
        # Use only target genes for leading edge tracking
        genes_to_track = set(target_genes)
        print(f"Tracking {len(genes_to_track)} target genes in leading edge")
    else:
        # Use all signature genes for leading edge tracking
        genes_to_track = set()
        for genes in signature_set.values():
            genes_to_track.update(genes)
        print(f"Tracking {len(genes_to_track)} signature genes in leading edge")

    # Process each term and comparison_category combination
    summary_rows = []

    # Check if comparison_category is available
    has_comparison_category = 'comparison_category' in res_deg_score.columns

    if has_comparison_category:
        # Group by both Term and comparison_category
        groupby_keys = ['Term', 'comparison_category']
    else:
        # Group by Term only
        groupby_keys = ['Term']

    for group_key, group_df in res_deg_score.groupby(groupby_keys):
        # Extract term and category
        if has_comparison_category:
            term, comparison_category = group_key
        else:
            term = group_key
            comparison_category = 'All'

        # Filter for significant results
        sig_df = group_df[group_df['FDR q-val'] < fdr_threshold]

        if len(sig_df) == 0:
            continue

        # Count significant comparisons for this term-category combination
        n_significant = len(sig_df)

        # Separate by NES direction
        pos_nes = sig_df[sig_df['NES'] > 0]
        neg_nes = sig_df[sig_df['NES'] < 0]

        # Get studies and NES values for each direction
        pos_studies = []
        neg_studies = []

        if len(pos_nes) > 0:
            for _, row in pos_nes.iterrows():
                pos_studies.append(f"{row['study']} (NES={row['NES']:.2f})")

        if len(neg_nes) > 0:
            for _, row in neg_nes.iterrows():
                neg_studies.append(f"{row['study']} (NES={row['NES']:.2f})")

        # Annotate leading edge genes
        # Check which target genes appear in leading edges
        leading_edge_targets = set()

        for _, row in sig_df.iterrows():
            if 'Lead_genes' in row and pd.notna(row['Lead_genes']):
                # Parse leading edge genes (format may vary)
                lead_genes_str = str(row['Lead_genes'])
                lead_genes = [g.strip() for g in lead_genes_str.split(';') if g.strip()]

                # Check intersection with target genes
                for gene in lead_genes:
                    if gene in genes_to_track:
                        leading_edge_targets.add(gene)

        # Create summary row
        summary_row = {
            'Term': term,
            'Comparison_Category': comparison_category,
            'N_Significant_Comparisons': n_significant,
            'Total_Comparisons': total_comparisons,
            'Percent_Significant': f"{(n_significant/total_comparisons*100):.1f}%",
            'N_Positive_NES': len(pos_nes),
            'N_Negative_NES': len(neg_nes),
            'Positive_NES_Studies': '; '.join(pos_studies) if pos_studies else 'None',
            'Negative_NES_Studies': '; '.join(neg_studies) if neg_studies else 'None',
            'Input_Targets_In_Leading_Edge': ', '.join(sorted(leading_edge_targets)) if leading_edge_targets else 'None',
            'N_Input_Targets_In_LE': len(leading_edge_targets)
        }

        summary_rows.append(summary_row)

    # Create summary dataframe
    summary_df = pd.DataFrame(summary_rows)

    if len(summary_df) > 0:
        # Sort by term and comparison category
        if has_comparison_category:
            summary_df = summary_df.sort_values(['N_Significant_Comparisons', 'Term', 'Comparison_Category'], ascending=[False, True, True])
        else:
            summary_df = summary_df.sort_values('N_Significant_Comparisons', ascending=False)

        # Save to file
        output_path = f"{output_dir}/{output_filename}"
        summary_df.to_csv(output_path, index=False)
        print(f"Saved enhanced GSEA summary to {output_path}")

        # Also save JSON version
        json_path = output_path.replace('.csv', '.json')
        export_json_file(summary_df, json_path)

        # Print summary statistics
        print(f"\nGSEA Summary Statistics:")
        if has_comparison_category:
            print(f"  Unique terms with FDR < {fdr_threshold}: {summary_df['Term'].nunique()}")
            print(f"  Term-Category combinations: {len(summary_df)}")
        else:
            print(f"  Terms with FDR < {fdr_threshold}: {len(summary_df)}")
        print(f"  Total comparisons: {total_comparisons}")
        print(f"\nTop 10 enriched term-category combinations by number of significant comparisons:")

        # Select columns to display
        display_cols = ['Term', 'Comparison_Category', 'N_Significant_Comparisons', 'N_Positive_NES', 'N_Negative_NES', 'N_Input_Targets_In_LE']

        print(summary_df[display_cols].head(10).to_string(index=False))
    else:
        print(f"No terms with FDR < {fdr_threshold} found")

    return summary_df


def compute_target_scores(detailed_df, output_dir, padj_threshold=0.05, output_filename='target_score_table.csv'):
    """Score and rank target genes based on weighted percentile-scaled log2fc.

    Only considers: Disease vs. Normal, Non-Responder vs. Responder, Responder vs. Non-Responder.
    Does not modify or filter any other pipeline output.
    """
    SCORE_CATEGORIES = ["Disease vs. Normal", "Non-Responder vs. Responder", "Responder vs. Non-Responder"]
    DIRECTION_WEIGHTS = {
        "Disease vs. Normal": 1,
        "Non-Responder vs. Responder": 1,
        "Responder vs. Non-Responder": -1,
    }
    SOURCE_WEIGHTS = {"internal": 50.0, "curated": 20.0, "omicsoft": 1.0}

    if 'comparison_category' not in detailed_df.columns:
        print("  Target scoring: no comparison_category column, skipping.")
        return detailed_df, None

    score_df = detailed_df[detailed_df['comparison_category'].isin(SCORE_CATEGORIES)].copy()
    if score_df.empty:
        print("  Target scoring: no matching comparison categories, skipping.")
        return detailed_df, None

    score_df['log2fc_gated'] = np.where(
        (score_df['padj'] < padj_threshold) & (score_df['log2fc'].abs() > 0),
        score_df['log2fc'], 0.0
    )

    def percentile_scale(group):
        vals = group['log2fc_gated']
        scaled = pd.Series(0.0, index=vals.index)
        pos_mask = vals > 0
        neg_mask = vals < 0
        if pos_mask.sum() > 0:
            pos_ranks = vals[pos_mask].rank(method='average')
            scaled[pos_mask] = pos_ranks / pos_ranks.max()
        if neg_mask.sum() > 0:
            neg_ranks = vals[neg_mask].abs().rank(method='average')
            scaled[neg_mask] = -(neg_ranks / neg_ranks.max())
        return scaled

    score_df['scaled_score'] = score_df.groupby(
        ['study', 'comparison'], group_keys=False
    ).apply(percentile_scale).values

    score_df['direction_weight'] = score_df['comparison_category'].astype(str).map(DIRECTION_WEIGHTS).fillna(0).astype(float)
    source_col = score_df['source'].astype(str) if 'source' in score_df.columns else 'omicsoft'
    score_df['source_weight'] = source_col.map(SOURCE_WEIGHTS).fillna(1.0) if isinstance(source_col, pd.Series) else 1.0
    score_df['weighted_score'] = score_df['scaled_score'] * score_df['direction_weight'] * score_df['source_weight']

    agg = score_df.groupby('Gene').agg(
        total_score=('weighted_score', 'sum'),
        n_comparisons=('weighted_score', 'count'),
        n_significant=('log2fc_gated', lambda x: (x != 0).sum()),
    ).reset_index()

    for cat, short_name in [("Disease vs. Normal", "disease_vs_normal_score"),
                            ("Non-Responder vs. Responder", "nonresp_vs_resp_score"),
                            ("Responder vs. Non-Responder", "resp_vs_nonresp_score")]:
        cat_scores = score_df[score_df['comparison_category'] == cat].groupby('Gene')['weighted_score'].sum()
        agg[short_name] = agg['Gene'].map(cat_scores).fillna(0.0)

    agg = agg.sort_values('total_score', ascending=False).reset_index(drop=True)
    agg.to_csv(f'{output_dir}/{output_filename}', index=False)
    print(f"Saved target score table to {output_dir}/{output_filename} ({len(agg)} genes)")

    merge_cols = ['scaled_score', 'direction_weight', 'source_weight', 'weighted_score']
    score_merge = score_df[['Gene', 'study', 'comparison'] + merge_cols]
    enhanced = detailed_df.merge(score_merge, on=['Gene', 'study', 'comparison'], how='left')
    for col in merge_cols:
        enhanced[col] = enhanced[col].fillna(0.0)

    return enhanced, agg


def run_analysis(args):
    """Main analysis function"""

    dt = datetime.now().strftime('%Y%m%d')

    # Set default output directory: {target}_{indication}_omicsoft_YYYYMMDD/ in current working directory
    # Avoid duplication when target_name == indication (e.g., IBD_IBD -> IBD)
    if args.output_dir is None:
        if args.indication and args.indication.lower() != args.target_name.lower():
            output_dir = f"{args.target_name}_{args.indication}_omicsoft_{dt}"
        else:
            output_dir = f"{args.target_name}_omicsoft_{dt}"
    else:
        output_dir = args.output_dir
    os.makedirs(output_dir, exist_ok=True)

    print("=" * 80)
    print(f"OMICSOFT DEG ANALYSIS - {args.target_name}")
    print("=" * 80)
    print(f"\nParameters:")
    print(f"  Target: {args.target_name}")
    print(f"  File: {args.file}")
    print(f"  Diseases: {args.diseases if args.diseases else 'None (all diseases)'}")
    print(f"  Studies: {args.studies if args.studies else 'None (all studies)'}")
    print(f"  Tissues: {args.tissues if args.tissues else 'None (all tissues)'}")
    print(f"  Comparison Category: {args.comparison_category if args.comparison_category else 'None (all categories)'}")
    print(f"  Case Treatment: {args.case_treatment if args.case_treatment else 'None (all treatments)'}")
    print(f"  Comparison: {args.comparison if args.comparison else 'None (all comparisons)'}")
    print(f"  Log2FC threshold: {args.lfc_threshold}")
    print(f"  Adjusted p-value threshold: {args.padj_threshold}")
    print(f"  Output directory: {output_dir}")
    print(f"  Run GSEA: {args.run_gsea}")
    print(f"  PathwayDB GSEA Only: {args.pathwaydb_gsea_only}")
    if args.indication:
        print(f"  Indication: {args.indication}")

    # Build filters dict for SOMA loading
    soma_filters = {}
    if args.diseases:
        soma_filters['diseases'] = args.diseases
    if args.exclude_diseases:
        soma_filters['exclude_diseases'] = args.exclude_diseases
    if args.tissues:
        soma_filters['tissues'] = args.tissues
    if args.studies:
        soma_filters['studies'] = args.studies
    if args.comparison_category:
        soma_filters['comparison_category'] = args.comparison_category
    if args.case_treatment:
        soma_filters['case_treatment'] = args.case_treatment
    if args.comparison:
        soma_filters['comparison'] = args.comparison

    # Load data (auto-detects SOMA vs h5ad)
    print(f"\n[1/5] Loading data file...")
    adata = load_data(args.file, filters=soma_filters if soma_filters else None)
    print(f"Loaded AnnData object: {adata.shape} (obs x vars)")
    print(f"  Observations: {adata.n_obs:,}")
    print(f"  Variables: {adata.n_vars:,}")

    # Filter data
    print(f"\n[2/5] Filtering data...")

    # Start with all observations (no filter)
    base_filter = pd.Series([True] * adata.n_obs, index=adata.obs.index)

    # Apply disease filter if provided
    if args.diseases:
        print(f"\nTotal diseases in dataset: {len(adata.obs.disease.unique())}")
        disease_pattern = '|'.join([d.strip() for d in args.diseases.split(',')])
        print(f"Filtering for diseases matching: {disease_pattern}")

        matching_diseases = [d for d in adata.obs.disease.unique()
                            if any(term.lower() in d.lower() for term in args.diseases.split(','))]

        print(f"Found {len(matching_diseases)} matching disease(s):")
        for disease in sorted(matching_diseases):
            count = (adata.obs.disease == disease).sum()
            print(f"  - {disease}: {count} observations")

        disease_filter = adata.obs.disease.str.contains(disease_pattern, case=False, na=False)
        base_filter = base_filter & disease_filter
        print(f"  Observations after disease filter: {base_filter.sum():,}")

    # Apply disease exclusion filter if provided
    if args.exclude_diseases:
        exclude_pattern = '|'.join([d.strip() for d in args.exclude_diseases.split(',')])
        print(f"\nExcluding diseases matching: {exclude_pattern}")

        # Get currently filtered observations
        temp_adata = adata[base_filter]
        excluded_diseases = [d for d in temp_adata.obs.disease.unique()
                            if any(term.lower() in d.lower() for term in args.exclude_diseases.split(','))]

        if excluded_diseases:
            print(f"Found {len(excluded_diseases)} disease(s) to exclude:")
            for disease in sorted(excluded_diseases):
                count = (temp_adata.obs.disease == disease).sum()
                print(f"  - {disease}: {count} observations")

        exclude_filter = ~adata.obs.disease.str.contains(exclude_pattern, case=False, na=False)
        base_filter = base_filter & exclude_filter
        print(f"  Observations after disease exclusion: {base_filter.sum():,}")

    # Apply study filter if provided
    if args.studies:
        study_list = [s.strip() for s in args.studies.split(',')]
        print(f"\nFiltering for studies: {study_list}")
        study_filter = adata.obs.study.isin(study_list)
        base_filter = base_filter & study_filter
        print(f"  Observations after study filter: {base_filter.sum():,}")

    # Apply tissue filter if provided
    if args.tissues:
        print(f"\nTotal tissues in dataset: {len(adata.obs.tissue.unique())}")
        tissue_pattern = '|'.join([t.strip() for t in args.tissues.split(',')])
        print(f"Filtering for tissues matching: {tissue_pattern}")

        matching_tissues = [t for t in adata.obs.tissue.unique()
                           if any(term.lower() in t.lower() for term in args.tissues.split(','))]

        print(f"Found {len(matching_tissues)} matching tissue(s):")
        for tissue in sorted(matching_tissues):
            count = (adata.obs.tissue == tissue).sum()
            print(f"  - {tissue}: {count} observations")

        tissue_filter = adata.obs.tissue.str.contains(tissue_pattern, case=False, na=False)
        base_filter = base_filter & tissue_filter
        print(f"  Observations after tissue filter: {base_filter.sum():,}")

    # Apply comparison category filter if provided
    if args.comparison_category:
        category_list = [c.strip() for c in args.comparison_category.split(',')]
        print(f"\nFiltering for comparison categories: {category_list}")
        category_filter = adata.obs.comparison_category.isin(category_list)
        base_filter = base_filter & category_filter
        print(f"  Observations after comparison category filter: {base_filter.sum():,}")

    # Apply case treatment filter if provided
    if args.case_treatment:
        treatment_list = [t.strip() for t in args.case_treatment.split(',')]
        print(f"\nFiltering for case treatments: {treatment_list}")
        treatment_filter = adata.obs.case_treatment.isin(treatment_list)
        base_filter = base_filter & treatment_filter
        print(f"  Observations after case treatment filter: {base_filter.sum():,}")

    # Apply comparison filter if provided
    if args.comparison:
        print(f"\nTotal comparisons in dataset: {len(adata.obs.comparison.unique())}")
        comparison_pattern = '|'.join([c.strip() for c in args.comparison.split(',')])
        print(f"Filtering for comparisons matching: {comparison_pattern}")

        matching_comparisons = [c for c in adata.obs.comparison.unique()
                               if any(term.lower() in c.lower() for term in args.comparison.split(','))]

        print(f"Found {len(matching_comparisons)} matching comparison(s):")
        for comparison in sorted(matching_comparisons):
            count = (adata.obs.comparison == comparison).sum()
            print(f"  - {comparison}: {count} observations")

        comparison_filter = adata.obs.comparison.str.contains(comparison_pattern, case=False, na=False)
        base_filter = base_filter & comparison_filter
        print(f"  Observations after comparison filter: {base_filter.sum():,}")

    # Remove duplicates
    base_filter = base_filter & ~adata.obs.index.duplicated()

    filtered_deg_adata = adata[base_filter]

    print(f"\nFiltered dataset: {filtered_deg_adata.shape}")
    print(f"  Observations: {filtered_deg_adata.n_obs:,}")
    print(f"  Variables: {filtered_deg_adata.n_vars:,}")

    if filtered_deg_adata.n_obs == 0:
        print("\nNo observations remain after filtering! Exiting.")
        return

    # Process disease categories
    print(f"\n[3/5] Processing disease categories...")
    filtered_deg_adata.obs['study'] = filtered_deg_adata.obs['study'].apply(lambda x: x.replace('/', '-'))
    filtered_deg_adata.obs['disease_category'] = filtered_deg_adata.obs.disease

    print(f"\nDisease categories: {len(filtered_deg_adata.obs.disease_category.unique())}")

    # Create study summary (include source column if available)
    summary_cols = ['study', 'tissue', 'disease', 'disease_category']
    has_source = 'source' in filtered_deg_adata.obs.columns
    if has_source:
        summary_cols.insert(1, 'source')
    study_df = filtered_deg_adata.obs.reset_index(drop=True).loc[:, summary_cols].drop_duplicates()
    print(f"Number of unique studies: {len(study_df)}")
    study_df.to_csv(f'{output_dir}/study_summary.csv', index=False)
    export_json_file(study_df, f'{output_dir}/study_summary.json')
    print(f"Saved study summary to {output_dir}/study_summary.csv")

    # Convert to long format (needed for GSEA)
    print(f"\n[4/5] Converting to long format...")
    long_df_comp = ad2long_df(filtered_deg_adata)
    print(f"Long format DataFrame shape: {long_df_comp.shape}")

    # Skip target/signature analysis if --pathwaydb-gsea mode
    if args.skip_target_analysis:
        print("\n[PathwayDB GSEA Only Mode] Skipping target/signature analysis...")
        signature_set = {}
        target_genes = None
        signature_set_for_plotting = {}
        signature_set_for_gsea = {}
    else:
        # Parse signature sets from user input
        # Format: "Sig1:Gene1,Gene2,Gene3;Sig2:GeneA,GeneB,GeneC"
        signature_set = {}
        if args.signatures:
            for sig_entry in args.signatures.split(';'):
                sig_entry = sig_entry.strip()
                if ':' not in sig_entry:
                    print(f"Warning: Skipping invalid signature format: {sig_entry}")
                    continue
                sig_name, genes = sig_entry.split(':', 1)
                gene_list = [g.strip() for g in genes.split(',') if g.strip()]
                if gene_list:
                    signature_set[sig_name.strip()] = gene_list
            print(f"\nParsed {len(signature_set)} signature(s):")
            for sig_name, genes in signature_set.items():
                print(f"  - {sig_name}: {len(genes)} genes")

        # Parse target genes if provided
        target_genes = None
        if args.targets:
            target_genes = [g.strip() for g in args.targets.split(',') if g.strip()]
            print(f"\nParsed {len(target_genes)} target gene(s) for leading edge tracking:")
            print(f"  Target genes: {', '.join(target_genes)}")
            print(f"  Note: Targets will be plotted but NOT included in GSEA enrichment")

        # Create signature_set_for_plotting that includes targets
        signature_set_for_plotting = signature_set.copy()
        if target_genes:
            signature_set_for_plotting['targets'] = target_genes

        # Keep original signature_set for GSEA (without targets)
        signature_set_for_gsea = signature_set.copy()

    if not args.skip_target_analysis and not signature_set_for_plotting:
        print("Warning: No signatures or targets provided, skipping signature analysis")
    elif not args.skip_target_analysis and signature_set_for_plotting:
        # Create scatter plots
        print(f"\nCreating scatter plots for {len(signature_set_for_plotting)} item(s)...")
        fig_dict = {}

        for sig, geneset in tqdm(signature_set_for_plotting.items(), desc="Creating scatter plots"):
            filtered_data = long_df_comp[
                (long_df_comp['Gene'].isin(sorted(geneset))) &
                (long_df_comp['padj'] < args.padj_threshold) &
                (abs(long_df_comp['log2fc']) > args.lfc_threshold)
            ]

            if len(filtered_data) == 0:
                print(f"No significant genes found for {sig}")
                continue

            fig_d = px.scatter(
                filtered_data,
                x="Gene", y="log2fc",
                size='-logpadj', color="disease_category", color_discrete_sequence=qualitative.Set3,
                hover_name="study",
                hover_data=['log2fc', 'padj', 'tissue', "disease_category", 'comparison', "case_treatment_status", "case_treatment_status"],
                size_max=25, title=f"{sig} log2fc", width=1200, height=600
            )
            fig_d.update_xaxes(categoryorder='category ascending')
            fig_d.add_hline(y=-args.lfc_threshold, line_dash="dot", line_color="green")
            fig_d.add_hline(y=args.lfc_threshold, line_dash="dot", line_color="green")
            fig_dict[sig] = fig_d

        # Create combined figure with dropdown
        if fig_dict:
            combined_fig = go.Figure()
            combined_fig.update_xaxes(tickfont=dict(size=20))
            combined_fig.update_yaxes(tickfont=dict(size=20))

            for i, (sig, fig) in enumerate(fig_dict.items()):
                for trace in fig.data:
                    combined_fig.add_trace(trace)
                    combined_fig.data[-1].visible = (i == 0)
                combined_fig.add_hline(y=-args.lfc_threshold, line_dash="dot", line_color="green", visible=(i == 0))
                combined_fig.add_hline(y=args.lfc_threshold, line_dash="dot", line_color="green", visible=(i == 0))

            # Create dropdown buttons
            dropdown_buttons = []
            for i, sig in enumerate(fig_dict.keys()):
                visibility = [False] * len(combined_fig.data)
                start_idx = sum(len(fig_dict[key].data) for key in list(fig_dict.keys())[:i])
                end_idx = start_idx + len(fig_dict[sig].data)
                for j in range(start_idx, end_idx):
                    visibility[j] = True

                dropdown_buttons.append(dict(
                    label=sig,
                    method="update",
                    args=[{"visible": visibility}, {"title": f"{sig} log2fc"}]
                ))

            combined_fig.update_layout(
                updatemenus=[dict(
                    active=0, buttons=dropdown_buttons, direction="down",
                    showactive=True, x=1, y=1
                )],
                legend=dict(itemsizing='constant', itemwidth=100),
                title="Select a signature from Dropdown"
            )

            combined_fig.write_html(f"{output_dir}/target_signature_{dt}.html")
            print(f"Saved interactive scatter plot to {output_dir}/target_signature_{dt}.html")

        # Create heatmaps for each signature
        print(f"\nCreating heatmaps...")
        heatmap_dict = {}

        # For each signature, generate heatmap traces
        for sig, geneset in tqdm(signature_set_for_plotting.items(), desc="Creating heatmaps"):
            title = f"{sig} log2fc"
            try:
                traces, annots, stored_title = lfc_heatmap_traces(
                    filtered_deg_adata, geneset, title,
                    lfc_limit=args.lfc_threshold,
                    padj_limit=args.padj_threshold
                )
                heatmap_dict[sig] = (traces, annots, stored_title)
            except Exception as e:
                print(f"Skipping {sig} due to error: {e}")
                continue

        # Create a combined figure
        if heatmap_dict:
            combined_heatmap = go.Figure()
            combined_fig.update_xaxes(tickfont=dict(size=20))
            combined_fig.update_yaxes(tickfont=dict(size=20))

            # Record the number of traces per signature for index calculation
            trace_counts = [len(heatmap_dict[key][0]) for key in heatmap_dict.keys()]
            total_traces = sum(trace_counts)

            # Add all traces to the combined figure with proper initial visibility
            for i, key in enumerate(heatmap_dict.keys()):
                for trace in heatmap_dict[key][0]:
                    combined_heatmap.add_trace(trace)
                    # Only show first signature initially
                    combined_heatmap.data[-1].visible = (i == 0)

            # Set initial layout annotations from the first signature
            first_key = list(heatmap_dict.keys())[0]
            combined_heatmap.update_layout(
                title=heatmap_dict[first_key][2],
                annotations=heatmap_dict[first_key][1],
                xaxis_title="Genes",
                yaxis_title="Samples"
            )

            # Create dropdown buttons to update visibility and layout annotations
            dropdown_buttons = []
            keys = list(heatmap_dict.keys())
            for i, sig in enumerate(keys):
                visibility = [False] * total_traces
                start_idx = sum(trace_counts[:i])
                end_idx = start_idx + trace_counts[i]
                for j in range(start_idx, end_idx):
                    visibility[j] = True
                dropdown_buttons.append(
                    dict(
                        label=sig,
                        method="update",
                        args=[
                            {"visible": visibility},
                            {"title": heatmap_dict[sig][2],
                             "annotations": heatmap_dict[sig][1]}
                        ]
                    )
                )

            combined_heatmap.update_layout(
                updatemenus=[dict(
                    active=0,
                    buttons=dropdown_buttons,
                    direction="down",
                    showactive=True,
                    x=1, y=1.05
                )],
                legend=dict(itemsizing='constant', itemwidth=100),
                title="Select a signature from Dropdown"
            )

            combined_heatmap.write_html(f"{output_dir}/comparison_signature_{dt}.html")
            print(f"Saved interactive heatmap to {output_dir}/comparison_signature_{dt}.html")
        else:
            print("No heatmaps generated")

        # Create summary table for all genes (signatures + targets)
        print(f"\nCreating {args.target_name} signature summary...")
        all_genes = list(set(g for dic in signature_set_for_plotting.values() for g in dic))

        sub_df = (
            long_df_comp[long_df_comp['Gene'].isin(all_genes)]
            .assign(sig=lambda x: np.where(
                (x['log2fc'] > args.lfc_threshold) & (x['padj'] < args.padj_threshold), 'up',
                np.where((x['log2fc'] < -args.lfc_threshold) & (x['padj'] < args.padj_threshold), 'dn', 'na')
            ))
            .groupby(['Gene', 'tissue', 'disease_category', 'comparison_category', 'sig'])
            .agg(count=('Gene', 'size'), study=('study', list))
            .reset_index()
            .assign(total_count=lambda df: df.groupby(['Gene', 'tissue', 'disease_category', 'comparison_category'])['count'].transform('sum'))
            .assign(threshold=f'|lfc|>{args.lfc_threshold};padj<{args.padj_threshold}')
            .query('count != 0 and sig != "na"')
        )

        if len(sub_df) > 0:
            # Renamed from signature_summary.csv to target_summary.csv
            # (file only contains target genes from --targets, not custom signature genes)
            sub_df.to_csv(f'{output_dir}/target_summary.csv', index=False)
            export_json_file(sub_df, f'{output_dir}/target_summary.json')
            print(f"Saved target summary to {output_dir}/target_summary.csv")
            print(f"\nTarget gene hits across diseases and comparison categories:")
            print(sub_df.groupby(['disease_category', 'comparison_category', 'tissue', 'sig'])['Gene'].count())
        else:
            print("No significant genes found in target summary analysis")

        # Export detailed long table for signature/target genes
        print(f"\nExporting detailed long table for signature/target genes...")
        detailed_long_df = long_df_comp[long_df_comp['Gene'].isin(all_genes)].copy()

        if 'source' not in detailed_long_df.columns:
            detailed_long_df['source'] = 'unknown'

        detailed_long_df.to_csv(f'{output_dir}/detailed_gene_table.csv', index=False)
        export_json_file(detailed_long_df, f'{output_dir}/detailed_gene_table.json')
        print(f"Saved detailed gene table to {output_dir}/detailed_gene_table.csv")
        print(f"  Shape: {detailed_long_df.shape} (rows x columns)")
        print(f"  Genes included: {detailed_long_df['Gene'].nunique()}")

        # Target scoring
        print(f"\nComputing target scores...")
        detailed_long_df, score_table = compute_target_scores(
            detailed_long_df, output_dir, padj_threshold=args.padj_threshold)
        detailed_long_df.to_csv(f'{output_dir}/detailed_gene_table.csv', index=False)
        export_json_file(detailed_long_df, f'{output_dir}/detailed_gene_table.json')

        # Generate per-signature score tables (same format as target_score_table + associated_target)
        if signature_set_for_gsea:
            print(f"\nGenerating per-signature score tables...")
            for sig_name, sig_genes in signature_set_for_gsea.items():
                sig_detailed = detailed_long_df[detailed_long_df['Gene'].isin(sig_genes)].copy()
                if sig_detailed.empty:
                    print(f"  {sig_name}: no genes in detailed table, skipping")
                    continue
                sig_out_filename = f'{sig_name}_score_table.csv'
                _, sig_score_table = compute_target_scores(
                    sig_detailed, output_dir, padj_threshold=args.padj_threshold,
                    output_filename=sig_out_filename)
                if sig_score_table is not None and len(sig_score_table) > 0:
                    sig_score_table = sig_score_table.assign(associated_target=sig_name.replace('_sig', ''))
                    sig_score_table.to_csv(f'{output_dir}/{sig_out_filename}', index=False)
                    print(f"  Saved {sig_out_filename} ({len(sig_score_table)} genes)")

        # Generate internal_vs_external_summary.csv (stratified by source)
        print(f"\nGenerating internal vs external summary...")
        SOURCE_WEIGHT_MAP = {'internal': 50.0, 'curated': 20.0, 'omicsoft': 1.0}
        try:
            source_summary_rows = []
            for (gene, source), grp in detailed_long_df.groupby(['Gene', 'source']):
                sig_mask = grp['padj'] < args.padj_threshold
                source_summary_rows.append({
                    'Gene': gene,
                    'source': source,
                    'n_comparisons': len(grp),
                    'n_significant': sig_mask.sum(),
                    'mean_log2fc': grp['log2fc'].mean(),
                    'median_log2fc': grp['log2fc'].median(),
                })

            source_summary_df = pd.DataFrame(source_summary_rows)

            # Add weighted aggregates section
            weighted_rows = []
            for gene, grp in detailed_long_df.groupby('Gene'):
                w = grp['source'].astype(str).map(SOURCE_WEIGHT_MAP).fillna(1.0).values
                lfc = grp['log2fc'].values
                sig_mask = grp['padj'] < args.padj_threshold
                weighted_rows.append({
                    'Gene': gene,
                    'source': 'WEIGHTED_AGGREGATE',
                    'n_comparisons': len(grp),
                    'n_significant': sig_mask.sum(),
                    'mean_log2fc': np.average(lfc, weights=w) if len(w) > 0 else np.nan,
                    'median_log2fc': grp['log2fc'].median(),
                })

            weighted_df = pd.DataFrame(weighted_rows)
            combined_summary = pd.concat([source_summary_df, weighted_df], ignore_index=True)
            combined_summary.to_csv(f'{output_dir}/internal_vs_external_summary.csv', index=False)
            export_json_file(combined_summary, f'{output_dir}/internal_vs_external_summary.json')
            print(f"Saved internal vs external summary to {output_dir}/internal_vs_external_summary.csv")
        except Exception as e:
            print(f"Warning: Could not generate internal_vs_external_summary: {e}")

    # GSEA Analysis
    if args.run_gsea:
        print(f"\n[5/5] Running GSEA analysis...")
        long_df_comp['padj'] = long_df_comp['padj'].replace(
            0,
            long_df_comp.loc[long_df_comp['padj'] > 0, 'padj'].min() / 10
        )
        enrich_df = long_df_comp.reset_index(drop=True).drop_duplicates().set_index('Gene')
        # Standardized GSEA ranking: -log10(padj) * sign(log2fc)
        # This puts upregulated genes at top (positive scores) and downregulated at bottom (negative scores)
        enrich_df['rank_score'] = -np.log10(enrich_df['padj'].clip(lower=1e-300)) * np.sign(enrich_df['log2fc'])

        res_deg_list = []

        # Skip standard GSEA when using --pathwaydb-gsea mode
        if not args.skip_target_analysis:
            # MSigDB_Hallmark_2020 is always included by default
            gsea_gene_sets = ['MSigDB_Hallmark_2020']

            print(f"GSEA will run with MSigDB_Hallmark_2020 (default) and {len(signature_set_for_gsea)} custom signature(s)")

            groupby_keys = ['study', 'comparison', 'comparison_category']
            for c, df in tqdm(enrich_df.groupby(groupby_keys), desc="Running GSEA"):
                study_id = str(c[0])
                comparison_val = str(c[1])
                study_comp = f"{study_id}: {comparison_val}"
                comp_category = c[2]

                # Get all metadata from first row
                metadata = get_group_metadata(df.reset_index(), groupby_keys)

                try:
                    # Standardized GSEA parameters: min_size=3, max_size=20000, seed=42
                    # Ranking: -log10(padj) * sign(log2fc) (descending: upregulated at top)
                    rank_series = df['rank_score'][df['rank_score'] != 0].sort_values(ascending=False)

                    # Skip comparisons with insufficient genes (all padj=1.0 gives rank=0)
                    if len(rank_series) < 100:
                        continue

                    # Run GSEA on custom signatures if provided (excluding targets)
                    if signature_set_for_gsea:
                        res_deg_enr = gp.prerank(
                            rnk=rank_series,
                            gene_sets=signature_set_for_gsea,
                            permutation_num=1000,
                            min_size=3,
                            max_size=20000,
                            threads=30,
                            seed=42,
                            outdir=None
                        )
                        res_deg_enr_df = res_deg_enr.res2d.assign(
                            study=study_id,
                            comparison=comparison_val,
                            study_comparison=study_comp,
                            comparison_category=comp_category,
                            **metadata
                        )
                        res_deg_list.append(res_deg_enr_df)

                    # Always run GSEA on MSigDB_Hallmark_2020
                    res_deg = gp.prerank(
                        rnk=rank_series,
                        gene_sets=gsea_gene_sets,
                        permutation_num=1000,
                        min_size=3,
                        max_size=20000,
                        threads=30,
                        seed=42,
                        outdir=None
                    )
                    res_deg_df = res_deg.res2d.assign(
                        study=study_id,
                        comparison=comparison_val,
                        study_comparison=study_comp,
                        comparison_category=comp_category,
                        **metadata
                    )
                    res_deg_list.append(res_deg_df)
                except:
                    print(f'skip {study_comp}')
        else:
            print("[PathwayDB GSEA Only Mode] Skipping standard signature/MSigDB GSEA...")

        if res_deg_list:
            res_deg_score = pd.concat(res_deg_list)

            # Reorder columns: GSEA results first, then priority metadata, then rest
            gsea_cols = ['Term', 'ES', 'NES', 'NOM p-val', 'FDR q-val', 'FWER p-val',
                         'Tag %', 'Gene %', 'Lead_genes']
            priority_meta = ['study', 'comparison', 'study_comparison', 'tissue', 'disease',
                             'disease_category', 'comparison_category', 'case_treatment',
                             'control_treatment', 'case_treatment_status', 'control_treatment_status']

            existing_gsea = [c for c in gsea_cols if c in res_deg_score.columns]
            existing_priority = [c for c in priority_meta if c in res_deg_score.columns]
            other_cols = [c for c in res_deg_score.columns if c not in gsea_cols + priority_meta]
            res_deg_score = res_deg_score[existing_gsea + existing_priority + other_cols]

            res_deg_score.to_csv(f'{output_dir}/gsea_all_results.csv', index=False)
            export_json_file(res_deg_score, f'{output_dir}/gsea_all_results.json')
            print(f"Saved GSEA results to {output_dir}/gsea_all_results.csv")

            # Create enhanced GSEA summary with leading edge annotation
            enhanced_summary_df = create_enhanced_gsea_summary(
                res_deg_score,
                signature_set_for_gsea,
                target_genes=target_genes,  # Pass target genes for leading edge tracking
                fdr_threshold=args.padj_threshold,
                output_dir=output_dir,
                output_filename='gsea_enhanced_summary.csv'
            )

            # Create GSEA scatter plot
            filtered_gsea = res_deg_score[(res_deg_score['NOM p-val'] < 0.05)]
            filtered_gsea['-logpadj'] = filtered_gsea['FDR q-val'].apply(lambda x: -np.log(x) if x != 0 else 0)

            fig_gsea = px.scatter(
                filtered_gsea,
                x="Term", y="NES",
                size='-logpadj', color="study", color_discrete_sequence=qualitative.Set3,
                hover_name="study",
                hover_data=['Term', 'NES', 'NOM p-val', "FDR q-val", "FWER p-val"],
                size_max=25, title=f"Pathway Enrichment Score", width=1600, height=800
            )
            fig_gsea.update_xaxes(categoryorder='category ascending')
            fig_gsea.add_hline(y=-1, line_dash="dot", line_color="green")
            fig_gsea.add_hline(y=1, line_dash="dot", line_color="green")
            fig_gsea.write_html(f"{output_dir}/gsea_score_pathway_{dt}.html")
            print(f"Saved GSEA scatter plot to {output_dir}/gsea_score_pathway_{dt}.html")

            # Auto-trigger report generation for target mode (not pathwaydb-gsea-only)
            if not args.pathwaydb_gsea_only:
                trigger_report_generation(args.target_name, args.indication, output_dir)

    # PathwayDB GSEA Analysis (using universal combined_pathways.csv)
    if args.pathwaydb_gsea_only:
        print(f"\n[PathwayDB GSEA] Running indication-centric pathway analysis...")
        print("  Using universal pathway database from /pathwaydb-query skill")

        # Load combined pathways from pathwaydb-query skill
        pathway_gene_sets, pathway_metadata = load_combined_pathways()

        if pathway_gene_sets is None:
            print("ERROR: Cannot proceed without combined_pathways.csv")
            print("  Run /pathwaydb-query skill first to generate the pathway database")
            sys.exit(1)

        try:
            # Prepare enrich_df for GSEA
            long_df_comp['padj'] = long_df_comp['padj'].replace(
                0,
                long_df_comp.loc[long_df_comp['padj'] > 0, 'padj'].min() / 10
            )
            enrich_df = long_df_comp.reset_index(drop=True).drop_duplicates().set_index('Gene')
            enrich_df['rank_score'] = -np.log10(enrich_df['padj'].clip(lower=1e-300)) * np.sign(enrich_df['log2fc'])

            # Run new pathwaydb GSEA (indication-centric, not target-coupled)
            # Use working directory (default: current directory) for timestamped output
            workdir = args.output_dir if args.output_dir else '.'
            pathwaydb_results = run_pathwaydb_gsea_new(
                enrich_df,
                pathway_gene_sets,
                pathway_metadata,
                indication=args.indication or 'Disease',
                workdir=workdir,
                n_workers=args.n_workers,
                export_json=args.export_json
            )

            if pathwaydb_results is not None and len(pathwaydb_results) > 0:
                print(f"\n  PathwayDB GSEA completed: {len(pathwaydb_results)} pathway-comparison results")
                # Note: No report generation in pathwaydb-gsea-only mode
        except Exception as e:
            print(f"Error running pathwaydb GSEA: {e}")
            import traceback
            traceback.print_exc()

    print("\n" + "=" * 80)
    print("ANALYSIS COMPLETE!")
    print("=" * 80)
    print(f"\nOutput files saved in {output_dir}/")


def trigger_report_generation(target_name, indication, output_dir):
    """
    Prepare context and print JSON instruction for Claude to spawn report team.

    This function:
    1. Creates a reports/ subdirectory for all report outputs
    2. Saves report_context.json with analysis context (target, indication, file paths)
    3. Prints a <gsea-report-instruction> JSON block for Claude to parse

    When Claude sees the JSON instruction in Bash output, it should:
    1. Read the prompt_file (gsea_report_prompt.md)
    2. Read the context_file (report_context.json)
    3. Create a background team with TeamCreate
    4. Spawn Opus agents following the workflow

    Parameters
    ----------
    target_name : str
        Target/analysis name (e.g., "GREM1", "IBD")
    indication : str or None
        Indication name (e.g., "IBD", "Fibrosis")
    output_dir : str
        Base output directory containing GSEA results
    """
    # Create reports subdirectory
    reports_dir = os.path.join(output_dir, 'reports')
    os.makedirs(reports_dir, exist_ok=True)

    # Build context for report generation
    indication_str = indication or target_name
    timestamp = datetime.now().strftime('%Y%m%d')

    # Find the pathwaydb output directory
    pathwaydb_dir = f'{indication_str}_pathwaydb_{timestamp}'
    pathwaydb_gsea_file = f'{pathwaydb_dir}/{indication_str}_pathwaydb_gsea.csv'

    # Check for available GSEA output files
    gsea_all_results = os.path.join(output_dir, 'gsea_all_results.csv')
    gsea_enhanced_summary = os.path.join(output_dir, 'gsea_enhanced_summary.csv')

    context = {
        'target': target_name,
        'indication': indication_str,
        'output_dir': os.path.abspath(output_dir),
        'reports_dir': os.path.abspath(reports_dir),
        'pathwaydb_dir': os.path.abspath(pathwaydb_dir) if os.path.exists(pathwaydb_dir) else pathwaydb_dir,
        'input_files': {
            'pathwaydb_gsea': pathwaydb_gsea_file,
            'pathwaydb_gsea_json': pathwaydb_gsea_file.replace('.csv', '.json'),
            'study_summary': os.path.join(output_dir, 'study_summary.csv'),
            'study_summary_json': os.path.join(output_dir, 'study_summary.json'),
            # Standard GSEA results (only present when using --signatures)
            'gsea_all_results': gsea_all_results if os.path.exists(gsea_all_results) else None,
            'gsea_enhanced_summary': gsea_enhanced_summary if os.path.exists(gsea_enhanced_summary) else None
        }
    }

    # Save context to JSON for Claude to read
    context_file = os.path.join(reports_dir, 'report_context.json')
    with open(context_file, 'w') as f:
        json.dump(context, f, indent=2)

    print(f"\nSaved report context to {context_file}")

    # Print JSON instruction block for Claude to parse
    instruction = {
        'action': 'spawn_gsea_report_team',
        'prompt_file': os.path.expanduser('~/.claude/skills/omicsoft-analysis/assets/gsea_report_prompt.md'),
        'context_file': os.path.abspath(context_file),
        'team_name': f'gsea-{target_name}-{indication_str}',
        'model': 'opus',
        'run_in_background': True,
        'agents': [
            {'name': 'disease-analyst', 'section': 'A'},
            {'name': 'target-specialist', 'section': 'B'},
            {'name': 'combo-strategist', 'section': 'C'},
            {'name': 'safety-analyst', 'section': 'D'}
        ],
        'output_dir': os.path.abspath(reports_dir)
    }

    print(f"\n{'='*80}")
    print("GSEA REPORT GENERATION INSTRUCTION")
    print(f"{'='*80}")
    print("<gsea-report-instruction>")
    print(json.dumps(instruction, indent=2))
    print("</gsea-report-instruction>")
    print(f"{'='*80}\n")

    return context_file


def main():
    parser = argparse.ArgumentParser(description='Omicsoft Bulk DEG Analysis')
    parser.add_argument('--file', required=True, help='Path to h5ad file')
    parser.add_argument('--target-name', required=True, help='Name of target gene/pathway for analysis')
    parser.add_argument('--signatures', required=False, default=None, help='Signatures in format "Name:Gene1,Gene2;Name2:GeneA,GeneB" (see references/signature_format.md). Required unless using --pathwaydb-gsea-only')

    # Optional target genes parameter
    parser.add_argument('--targets', default=None, help='Optional: Comma-separated list of target genes for tracking in leading edge and plotting (e.g., "GENE1,GENE2,GENE3"). These will be plotted but NOT included in GSEA enrichment.')

    # Optional filtering parameters
    parser.add_argument('--diseases', default=None, help='Optional: Comma-separated list of disease keywords to filter (e.g., "scleroderma,sclerosis")')
    parser.add_argument('--exclude-diseases', default=None, help='Optional: Comma-separated list of disease keywords to exclude (e.g., "ALS,amyotrophic lateral sclerosis")')
    parser.add_argument('--studies', default=None, help='Optional: Comma-separated list of study names to filter (e.g., "GSE12345,GSE67890")')
    parser.add_argument('--tissues', default=None, help='Optional: Comma-separated list of tissue keywords to filter (e.g., "skin,blood,lung")')
    parser.add_argument('--comparison-category', default=None, help='Optional: Comma-separated list of comparison categories to filter (e.g., "Disease vs. Normal")')
    parser.add_argument('--case-treatment', default=None, help='Optional: Comma-separated list of treatment keywords to filter (e.g., "none,NA")')
    parser.add_argument('--comparison', default=None, help='Optional: Comma-separated list of comparison keywords for fuzzy/partial matching (e.g., "response vs no response")')

    parser.add_argument('--lfc-threshold', type=float, default=0.0, help='Absolute log2 fold change threshold (default: 0.0)')
    parser.add_argument('--padj-threshold', type=float, default=0.05, help='Adjusted p-value threshold (default: 0.05)')
    parser.add_argument('--output-dir', default=None, help='Output directory (default: {target_name}_omicsoft/ in current working directory)')
    parser.add_argument('--run-gsea', action='store_true', default=True, help='Run GSEA analysis (ON by default, includes MSigDB_Hallmark_2020)')
    parser.add_argument('--no-gsea', action='store_true', help='Disable GSEA analysis')
    parser.add_argument('--pathwaydb-gsea-only', action='store_true', help='Run ONLY PathwayDB GSEA (indication-centric). Skips target/signature analysis, default MSigDB GSEA, and report generation.')
    parser.add_argument('--indication', default=None, help='Indication name for output directory naming (e.g., "IBD", "Fibrosis"). Used in output path: {target}_{indication}_omicsoft_YYYYMMDD/')
    parser.add_argument('--n-workers', type=int, default=24, help='Number of parallel workers for GSEA (default: 24)')
    parser.add_argument('--export-json', action='store_true', default=False,
                        help='Export JSON files alongside Parquet (default: False, Parquet only)')

    args = parser.parse_args()

    # Validate --signatures is required unless using --pathwaydb-gsea-only
    if not args.pathwaydb_gsea_only and not args.signatures:
        parser.error("--signatures is required unless using --pathwaydb-gsea-only")

    # Handle GSEA flag logic
    if args.no_gsea:
        args.run_gsea = False

    # PathwayDB GSEA only mode: skip standard GSEA, skip target analysis, no report
    if args.pathwaydb_gsea_only:
        args.run_gsea = False  # Disable standard GSEA (MSigDB + signatures)
        args.skip_target_analysis = True  # Skip target/signature analysis
    else:
        # Target mode: run standard GSEA (default ON)
        args.run_gsea = True
        args.skip_target_analysis = False

    run_analysis(args)


if __name__ == "__main__":
    main()
